<div class="opennotificationGreen" style="z-index: 99;">
    <span class="notification_msgGreen">Changes saved successfully.</span>
</div>
<div id="content">
    <h3> </h3>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget widget-tabs border-bottom-none">

            <!-- Widget heading -->
            <div class="widget-head">
                <ul>
                    <li class="active"><a class="glyphicons edit"  data-toggle="tab"><i></i>Player Salary Setting</a></li>
                </ul>
            </div>
            <!-- // Widget heading END -->


            <div class="widget-body">
                <form class="form-horizontal margin-none editdisabilityform_removeforvalidation" method="post">
                    <div class="tab-content pad0">

                        <!-- Tab content -->
                        <div class="tab-pane active" >

                            <!-- Row -->
                            <div class="row-fluid">

                                <!-- Column -->
                                <div class="span6">
								
									<div class="control-group">
                                        <label style="width: 32%;" class="control-label">Max Salary Amount</label>
                                        <div class="controls">
                                            <input type="text" name="max_salary_amount"  value="<?php echo (!empty($this->PlayerSettings['max_salary_amount']))?$this->PlayerSettings['max_salary_amount']:""; ?>" class="span10" /> 	
                                        </div>
                                    </div>
									
									<div class="control-group">
                                        <label style="width: 32%;" class="control-label">Min Salary Amount</label>
                                        <div class="controls">
                                            <input type="text" name="min_salary_amount"  value="<?php echo (!empty($this->PlayerSettings['min_salary_amount']))?$this->PlayerSettings['min_salary_amount']:""; ?>" class="span10" /> 	
                                        </div>
                                    </div>
									
                                    <div class="control-group">
                                        <label class="control-label" style="width: 32%;">Player FPPG</label>
                                        <div class="controls">
                                            <input type="text" name="plr_fppg"  required="true"  value="<?php echo (!empty($this->PlayerSettings['plr_fppg']))?$this->PlayerSettings['plr_fppg']:""; ?>" class="span10" />
                                        </div>
                                    </div>
                                    <!-- // Group END -->
									
									<!-- Group -->
                                    <div class="control-group">
                                        <label style="width: 32%;" class="control-label">Salary Amount Increase</label>
                                        <div class="controls">
                                            <input type="text" name="salary_amount"  value="<?php echo (!empty($this->PlayerSettings['salary_amount']))?$this->PlayerSettings['salary_amount']:""; ?>" class="span10" /> 	
                                        </div>
                                    </div>
									
                                    <!-- Group -->
                                    <div class="control-group">
                                        <label class="control-label" style="width: 32%;" >Status</label>
                                        <div class="controls">
                                            <select class="span4" name="status">
                                                <?php if ($this->PlayerSettings['status'] == 1) { ?>
                                                    <option selected="true" value="1">Active</option>
                                                    <option value="0">Deactive</option>          
                                                <?php } else { ?>
                                                    <option  value="1">Active</option>
                                                    <option selected="true" value="0">Deactive</option>          
                                                <?php } ?>
                                            </select>										

                                        </div>
                                    </div>
                                    <!-- // Group END -->   
                                </div>
                                <!-- // Column END -->
                            </div>
                            <!-- // Row END -->

                            <div class="separator line bottom"></div>
                            <!-- Form actions -->
                            <div class="form-actions" style="margin-left:17%;">
                                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button>
                                <a style="margin-left:1%;" href="<?php $this->baseUrl(); ?>/admin/player-details">	<button type="button" class="btn btn-icon btn-default glyphicons circle_remove"><i></i>Cancel</button> </a>
                            </div>
                            <!-- // Form actions END -->

                        </div>
                        <!-- // Tab content END -->
                    </div>
                </form>
            </div>
        </div>
        <!-- // Widget END -->
    </div>	
</div>

<script>
    $('#menu_components4').removeClass('collapse').addClass('in collapse');
    $('#player_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons group active');
    $('#player_salary_setting').addClass('active');  
</script>

<?php if (isset($this->success)) { ?>
    <!-- This script Displays the  notification when the user details are submitted on submit  -->
    <script>  
        $('.opennotificationGreen').click(function()
        {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        });
        
        $('.opennotificationGreen').fadeIn("slow");             
        $('.opennotificationGreen').css('display','block');
            
        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        }, 3000);               
    </script>
<?php
}?>