<div id="content">
	<h4>Player Details</h4>
	<div class="innerLR">
		<!-- Widget -->
		<div class="widget">
			<!-- Widget heading -->
			<div class="widget-head">
				<h4 class="heading">Player Manage</h4>
			</div>
			<!-- // Widget heading END -->
			<div class="widget-body">
				<div class="row-fluid">
					<!-- Group -->
						<div class="control-group">
							<label class="control-label span1">Sports :-</label>
							<div class="controls">
							   
								<select id="selectsport" class="span4">
									<option class="sport" value="">SELECT SPORTS</option>
									<?php if(isset($this->activesport)){
										foreach($this->activesport as $sport){ ?> 
										   
									 <option class="sport" value="<?php echo $sport['sports_id']; ?>"><?php echo $sport['display_name']; ?></option>
												 <?php  }
									} ?>
								</select>
							</div>
						</div>
					<!-- // Group END -->
				</div>
			
				<div class="row-fluid" style="display:none;" id="team_menu">
					<!-- Group -->
						<label class="control-label span1">Team :-</label>
						<div class="control-group">
							<select id="selectteam" class="span4">
									
							</select>
						</div>
					<!-- // Group END -->
				</div>
				<div class="row-fluid" id="plydetails" style="display: none;">
						   
					<!-- Table -->
					<table id="plr_table2"  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
					
						<!-- Table heading -->
						<thead>
							<tr>
								<th class="center">No</th>
								<th class="center">Name</th>
								<th class="center">Position</th>
								<th class="center">Fppg</th>
								<th class="center">Player Value</th>
								<th class="center">Team Name</th>
								<th class="center">Action</th>
							</tr>
						</thead>
						<!-- // Table heading END -->
						
						<!-- Table body -->
						<tbody class="plr_table"></tbody>
						<!-- // Table body END -->
						
						<tfoot class="footable-pagination">
							<tr>
								<td colspan="8"><ul id="pagination" class="footable-nav" /></td>
							</tr>
						</tfoot>
					</table>
							
					<!-- // Table END -->
				</div>
			</div>
		</div>
	</div>
</div>	


<input type="hidden" id="sportId" value="">

<script type="text/javascript">
    $('#menu_components4').removeClass('collapse').addClass('in collapse');
    $('#player_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons group active');
    $('#player_detail_menu').addClass('active');   


	$('#selectsport').on('change',function(e){
		var sports_id = $('#selectsport').val();            
		$(".plr_table").html('');
		$("#selectteam").html('');
		$("#team_menu").css('display', 'none') ;
		$("#plydetails").css('display', 'none') ;
		$.ajax({

			url      : '/admin/player-details',
			type     : 'POST',
			dataType : 'json',
			data : {                
				sport : sports_id,
				method : "getTeams"
			},
			beforeSend : function() {

			},
			success : function(response) {
				//response = JSON.parse(response);
				console.log(response);
				if(response){
					$("#team_menu").css('display', '') ;
					$("#selectteam").append('<option value="">SELECT TEAM</option>');
					$.each(response,function( index, value ) {
						$("#selectteam").append('<option value="'+index+'">'+value+'</option>');
					});
					/*  $('#new_contest_table').dataTable({
						paging: true
					}); */
				}
					  
			}

		});   
	});

	$('#selectteam').on('change',function(e){
        var team = $('#selectteam').val();   
		var sports_id = $('#selectsport').val();
  
        $.ajax({

            url      : '/admin/player-details',
            type     : 'POST',
            dataType : 'json',
            data : {                
                team : team,
                sport : sports_id,
				method : "getPlayers"
            },
            beforeSend : function() {

            },
            success : function(response) {
				//response = JSON.parse(response);
				var inc = 1;
				console.log(response);
				if(response){
                    $("#plydetails").css('display', '') ;
					$("#plr_table2").dataTable().fnDestroy();
					$(".plr_table").html('');
					$.each(response,function( index, value ) {
						var plr_details = JSON.parse(value.plr_details);
						
						$(".plr_table").append('<tr><td class="center">'+inc+'</td><td class="center" >'+plr_details.name+'</td><td class="center" >'+plr_details.position+'</td><td class="center" >'+value.fppg+'</td><td class="center" >'+value.plr_value+'</td><td class="center">'+plr_details.team_name+'</td><td class="center"><a href="/admin/edit-disability/'+value.plr_id+'@'+value.gmp_id+'">Edit</a></td></tr>');
						
						inc = inc + 1;
                    });
					
					
					$('#plr_table2').dataTable({
						paging: true
					});
				}
            }
			
        }); 
    });

</script>