<div class="panel-space header_space" style="font-size:20px;">My Lineups</div>
<div class="row tpspace">
    
    <div class="col-md-6">
    <div class="button_bg">
            <div class="menu_head btn btn-warning" style="cursor:pointer;">Filter View</div>
                <ul class="menu_body">
                   
                <ul class="divid">
                    <a id="filter-clear-all" class="chk alt_brder" href="#" name="uncheckall"  style="color:#A3FF47"; value="uncheckall">Clear All</a>
                    
<!--                     <i class="chk ">CLEAR ALL</i>-->
                    <i class="chk alt_brder"style="color:#ff9900";>SPORT TYPE</i>                    
                    <i class="chk allcheck alt_brder"><input name="check_list" type="checkbox">ALL SPORTS</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="0">NFL</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="1">NBA</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="2">MLB</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="3">NHL</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="4">PGA</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="5">CBB</i>
                    <i class="chk checksport alt_brder"><input type="checkbox" name="check_list" value="6">CFB</i>
                </ul>
            
                <ul class="divid">
<!--                    <i class="chk"></i>-->
                    <i class="chk check_brder" style="color:#ff9900";>LINEUP STATUS</i>
                    <i class="chk allcheck check_brder"><input type="checkbox"    name="check_list"value="0">ALL STATUS</i>
                    <i class="chk checkstatus check_brder"><input type="checkbox"  name="check_list" value="1">NEW</i>
                    <i class="chk checkstatus check_brder"><input type="checkbox"  name="check_list"value="2">UPCOMING</i>
                    <i class="chk checkstatus check_brder"><input type="checkbox"  name="check_list"value="3">LIVE</i>
                    <i class="chk checkstatus check_brder"><input type="checkbox" name="check_list"  value="4">COMPLETE</i>
                    <i class="chk check_brder"><button type="button" class="btn btn-warning buttonapply " id="apply_filter">APPLY FILTER</button></i>
                    <i class="chk check_brder"><button type="button" class="btn btn-default buttonclose">CLOSE</button></i>
                </ul>
            
            </ul>
          </div>
    </div>
  <div class="col-md-6">
     <ul class="nav nav-tabs togTabsLineup pull-right">
         <li id="my_lineup" class="active"><a href="/lineup" id="myline">My Lineup</a></li>
         <li id="createlineup" class="active"><a href="#newlineup" id="create_new_lineup" data-toggle="tab">Create New Lineup</a></li>
        <li id="globalplayer"><a href="#gps" data-toggle="tab">Global Player Swap</a></li>
     </ul>
  </div>
    <div id="message" style="display:none;">
        <h4 style="color:#3B5E7A; margin-top: 100px; margin-bottom: 100px"><strong><center><?php if(isset($this->message)){echo $this->message; } ?></center></strong></h5>
    </div>
</div>
    <div class="tab-content">
<!--      <div class="tab-pane active " id="mylineup">
          
          <div class="row">
              <?php if (isset($this->lineupdetails)) {
                  foreach ($this->lineupdetails as $lkey => $lineup) { ?>
                      <div class="col-xs-6 col-md-4 well_mylineups lineup">
                          <div class="col-xs-6 col-md-12 spt_bg_1 color_white">
                              <span><big><strong class="sportname"><?php
                                          if (isset($lineup['sports_id'])):
                                              switch ($lineup['sports_id']):
                                                  case 1 : echo "NFL";
                                                      break;
                                                  case 2 : echo "MLB";
                                                      break;
                                                  case 3 : echo "NBA";
                                                      break;
                                                  case 4 : echo "NHL";
                                                      break;
                                              endswitch;
                                          endif;
                                          ?></strong></big></span> 
                              <span class="pull-right"><strong class="con_status"><?php if ($lineup['con_status'] == 0) {
                                              echo "UPCOMING";
                                          } elseif ($lineup['con_status'] == 1) {
                                              echo "COMPLETED";
                                          } elseif ($lineup['con_status'] == 2) {
                                              echo "LIVE";
                                          } ?> </strong><span data-time="<?php echo strtotime($lineup['start_time']); ?>" class="timeleft"></span> </span><br/>

                              <span><strong># of entries:</strong></span> <span class="text-center"><strong>PIR:</strong></span><span class="pull-right"><strong>Rem. Salary:</strong></span><br/>
                              <span class="linespan"><?php if (isset($lineup['entries'])) {
                                              echo $lineup['entries'];
                                          } ?></span> <span class="linespan">90</span><span class="linespan"><?php if (isset($lineup['rem_salary'])) {
                                              echo "$" . $lineup['rem_salary'];
                                          } ?></span>
                          </div>
                          <table class="table table-bordered">
                              <thead>
                                  <tr>
                                      <th>Pos</th><th>Player</th><th>FPPG</th><th></th>
                                  </tr>
                              </thead>    
                              <tbody>
                                      <?php foreach ($lineup['player_details'] as $pkey => $player) { ?>
                                      <tr>                             
                                          <td><?php echo $player['position']; ?></td>
                                          <td><a style="color:#fff;" href="#" class="playerDetails" data-target="#playerDetailsModal" data-toggle="modal" data-pid="<?php echo $player['id']; ?>"><?php echo $player['name']; ?></a></td>
                                          <td><?php if (isset($lineup['player_point'])) {
                                                   echo $lineup['player_point'];
                                                  } else {
                                                     echo "4.4";
                                                   } ?></td>
                                                                    Name:Sarika Nayak
                                                                        date:4/8/2014
                                                                        description:to show a lock image if contest_status is live or completed
            <?php if (($lineup['con_status'] == 1) || ($lineup['con_status'] == 2)) { ?>
                                              <td> <a href="#"><img   src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . 'images/lock.png'; ?>" alt="" /></a></td>                
            <?php } else { ?>
                                              <td> <a href="#"><img class="editLineup" data-val="<?php echo $lineup['lineup_id'] . '@' . $player['id']; ?>" src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . 'images/cross2.png'; ?>" alt="" /></a></td>
            <?php } ?>
                                      </tr>
        <?php } ?>
                              </tbody>
                          </table>
                          <div class="center">LAST EDIT :- <?php if (isset($lineup['created_date'])) {
            echo date('M d Y,  H:i A ', strtotime($lineup['created_date'])) . "EST";
        } ?></div>
                          <div class="btn-toolbar" role="toolbar">
                              <div class="btn-group btn-group-xs">
                                  <button   data-val="<?php echo $lineup['lineup_id']; ?>" type="button" class="btn btn-info editLineup" <?php if (($lineup['con_status'] == 1) || ($lineup['con_status'] == 2)) { ?> disabled="true" <?php } ?> >EDIT</button>
                              </div>

        <?php if ($lineup['con_status'] == 0) { ?>                    
                                  <div class="btn-group btn-group-xs">

                                      <button type="button" data-val="<?php echo $lineup['lineup_id']; ?>" class="btn btn-info export">EXPORT</button>
                                  </div>
                                  <div class="btn-group btn-group-xs">
                                      <button type="button" data-val="<?php echo $lineup['lineup_id']; ?>" class="btn btn-info entrysLineup">JOIN CONTESTS</button>
                                  </div>
                                  <div class="btn-group btn-group-xs">
                                      <button type="button" class="btn btn-info challenge" data-sport-val="<?php echo $lineup['sports_id']; ?>"  data-val="<?php echo $lineup['lineup_id']; ?>" data-toggle="modal">CHALLENGE</button>
                                  </div>
        <?php } ?>    
                          </div>

                      </div>              
    <?php }
} ?> 
              sample lineup static

              /end test lineups/
          </div>
 <div id="pd-slot"></div>          
      
      </div>  -->
      <div class="tab-pane active" id="newlineup">
          <div class="panel panel-default">
              <div class="panel-heading">
                  <div class="row">
                      <div class="col-md-5">    
                           <h3 class="panel-title">Create New Lineup</h3>
                      </div>
                      <div class="close-button controls">
                        <a class="panel-close12" href="/lineup">
                        <img src="/assets/images/Cross_red.png">
                        </a>
                      </div>
                      <div id="CreateNewLineup" class="col-md-12">
                          
                      </div>
                      
                      
                  </div>
            </div>
            <div class="panel-body" id="mynewlineup">
              <h5>There are a few things we need to know before you can begin building your lineup. The questions below help us determine which players are available for drafting in the next step.</h5>
              <div class="lineup-form controls">
                  <h4>1. What sport do you wish to create a lineup for?</h4>
                  <div class="choose-sport">
                      <p>
<!--                         <label><input type="radio" value="5" name="contest-type">NBA</label>
                          <label><input type="radio" value="7" name="contest-type">CBB</label>
                          <label><input type="radio" value="8" name="contest-type">NHL</label>
                          <label><input type="radio" value="9" name="contest-type">PGA</label>
                          <label><input type="radio" value="12" name="contest-type">MLB</label>-->
                      </p>
                  </div>
                  <div class="step2" style="display: block;">
                      <h5><strong>There are multiple contest start times currently listed for the sport you've selected. Please select a start time.</strong></h5>
                      <div class="choose-start-date">
                          <p>
<!--                              <label><input type="radio" data-end-date="/Date(1396058220000)/" data-start-date="/Date(1395962100000)/" value="1" name="contest-start-date">3/28 4:45am (8 games)</label>
                              <label><input type="radio" data-end-date="/Date(1396058220000)/" data-start-date="/Date(1396048500000)/" value="1" name="contest-start-date">3/29 4:45am (4 games)</label>-->
                          </p>
                      </div>
                  </div>
                
                  <button type="button" id="continue" style="display: none; margin-left:12px;" class="btn btn-warning pull-right" >Continue</button>
                  <a href="/lineup"><button type="button" id="cancel_li_bt" class="btn btn-default pull-right">Cancel</button></a>
                  
              </div>
            </div>
         </div>
      </div>
      <div class="tab-pane" id="gps">
          
      </div>
    </div> 
     
    </div>
  </div>
</div>
<!--Sarika Nayak
date: 29/08/2014
description: to solve bug no. 270-->
<div class="modal fade contest-details-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="contest-details-content">

        </div>
    </div>
</div>
<script>
 $(document).ready(function(){
    
     $.ajax({

                        url      : './ajax-handler-lineup',
                        type     : 'POST',
                        dataType : 'json',
                        data : {
                            method : 'sportslist'
               
                        },
                        beforeSend : function() {

                        },
                        success : function(response) {
                 
                            //console.log(response); return;
                            $('.choose-sport').html('<p></p>');
                            var i = 0;
                            $( response ).each(function( index, value ) {
                                //   alert(value.display_name);
                                //                         console.log(value);
                                //  console.log(value.display_name);
                                //   display_name
                                $('.choose-sport > p').append('<label class="radio-inline"><input type="radio" class="game" data-gameno="'+i+'" name="game_name" value="'+value.sports_id+'">'+value.display_name+'</label>');
                         
                                $('.choose-start-date > p').append('<div id="game'+i+'" class="gamedis" style="display:none;">');
                                $.each(value.time, function( index1, value1 ) {                         
                         
                                    $('.choose-start-date > p > #game'+i+' ').append('<label class="radio-inline"><input type="radio" class="gametime" name="gamedate" value="'+index1+'">'+index1+'('+value1+' games)</label><br/>');    
                             
                                                //console.log(index1);
                                                //console.log(value1);
                                });
                                i++;
                                $('.choose-start-date > p').append('</div>');
                            });
                        }

                    });
    
  $("#createlineup").click(function(){
    $("#message").hide();
  });
  $("#globalplayer").click(function(){
    $("#message").hide();
  });
   $("#my_lineup").click(function(){
    $("#message").show();
  });
});
$(document).ready(function(){
    $(".buttonclose").click(function(){
       $(".menu_body").hide();  
    });
    
            $( "#createlineup" ).tab('show');
            //$('#createlineup').trigger();
            // $(this).tab('show')
});

$(document).ready(function(){
    $("#filter-clear-all").click(function () {
 
	$('input:checkbox[name=check_list]').attr('checked',false);
 
    });	
 
  });

       
    
</script>
