<style>
    .contactusform #subject-error .help-block {
        margin-left: 0;
    }
    .contactusform #message-error .help-block {
        margin-left: 19%;
    }
    .contactusform #uname-error .help-block {
        margin-left: 14%;
    }
    .input-bg-black {
    -moz-appearance: window;
    background-color: rgba(255, 255, 255, 0.2);
}
 .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {
        background-color: rgba(255, 255, 255, 0.2);
    }
.input-bg-black {
   
    border: medium none !important;
    color: #fff;
}
</style>
<style>
.discord-widget{
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
.discord-widget div, .discord-widget span, .discord-widget applet,
.discord-widget object, .discord-widget iframe,
.discord-widget h1, .discord-widget h2, .discord-widget h3,
.discord-widget h4, .discord-widget h5, .discord-widget h6,
.discord-widget p, .discord-widget blockquote, .discord-widget pre,
.discord-widget a, .discord-widget abbr, .discord-widget acronym,
.discord-widget address, .discord-widget big, .discord-widget cite,
.discord-widget code, .discord-widget del, .discord-widget dfn,
.discord-widget em, .discord-widget img, .discord-widget ins,
.discord-widget kbd, .discord-widget q, .discord-widget s,
.discord-widget samp, .discord-widget small, .discord-widget strike,
.discord-widget strong, .discord-widget sub, .discord-widget sup,
.discord-widget tt, .discord-widget var, .discord-widget b,
.discord-widget u, .discord-widget i, .discord-widget center,
.discord-widget dl, .discord-widget dt, .discord-widget dd,
.discord-widget ol, .discord-widget ul, .discord-widget li,
.discord-widget fieldset, .discord-widget form, .discord-widget label,
.discord-widget legend, .discord-widget table, .discord-widget caption,
.discord-widget tbody, .discord-widget tfoot, .discord-widget thead,
.discord-widget tr, .discord-widget th, .discord-widget td,
.discord-widget article, .discord-widget aside, .discord-widget canvas,
.discord-widget details, .discord-widget embed, .discord-widget figure,
.discord-widget figcaption, .discord-widget footer, .discord-widget header,
.discord-widget hgroup, .discord-widget menu, .discord-widget nav,
.discord-widget output, .discord-widget ruby, .discord-widget section,
.discord-widget summary, .discord-widget time, .discord-widget mark,
.discord-widget audio, .discord-widget video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: middle;
}
/* HTML5 display-role reset for older browsers */
.discord-widget article, .discord-widget aside, .discord-widget details,
.discord-widget figcaption, .discord-widget figure, .discord-widget footer,
.discord-widget header, .discord-widget hgroup, .discord-widget menu,
.discord-widget nav, .discord-widget section {
  display: block;
}
.discord-widget body {
  line-height: 1;
}
.discord-widget ol, .discord-widget ul {
  list-style: none;
}
.discord-widget blockquote, .discord-widget q {
  quotes: none;
}
.discord-widget blockquote:before, .discord-widget blockquote:after,
.discord-widget q:before, .discord-widget q:after {
  content: '';
  content: none;
}
.discord-widget table {
  border-collapse: collapse;
  border-spacing: 0;
}


.discord-widget{
  background: #2a2a2a;
  color: #aaa;
  text-align:left;
  padding: 15px;
  margin:4px;
  font-size: 14px;
  font-weight: 500;
  position:relative;
  -webkit-box-shadow: 0 1px 5px rgba(0,0,0,0.4);
  -moz-box-shadow: 0 1px 5px rgba(0,0,0,0.4);
  box-shadow: 0 1px 5px rgba(0,0,0,0.4);
  border: 3px solid #2461b2;
  border-width: 0;
  border-top-width: 3px;
  box-sizing: border-box;
}
span.discord-error {
  color: red;
  font-size: 1.25em;
}
.discord-fade{
  pointer-events: none !important;
  position: absolute;
  top: 35px;
  bottom: 0;
  left: 0;
  width: 100%;
  background: -moz-linear-gradient(left,  rgba(42,42,42,0) 0%, rgba(42,42,42,0) 97%, rgba(42,42,42,1) 100%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(42,42,42,0)), color-stop(97%,rgba(42,42,42,0)), color-stop(100%,rgba(42,42,42,1)));
  background: -webkit-linear-gradient(left,  rgba(42,42,42,0) 0%,rgba(42,42,42,0) 97%,rgba(42,42,42,1) 100%);
  background: -o-linear-gradient(left,  rgba(42,42,42,0) 0%,rgba(42,42,42,0) 97%,rgba(42,42,42,1) 100%);
  background: -ms-linear-gradient(left,  rgba(42,42,42,0) 0%,rgba(42,42,42,0) 97%,rgba(42,42,42,1) 100%);
  background: linear-gradient(to right,  rgba(42,42,42,0) 0%,rgba(42,42,42,0) 97%,rgba(42,42,42,1) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#002a2a2a', endColorstr='#2a2a2a',GradientType=1 );
}
.discord-title{
  margin: -15px!important;
  margin-bottom: 5px!important;
  height: 32px;
  line-height: 32px!important;
  background-color: #333;
  border: solid 1px #222!important;
  padding-left: 10px!important;
  font-weight: bold!important;
  font-size:1.17em!important;
}
.discord-tree{
  padding-left:0;
  margin-top: 24px;
  margin-bottom:0;
  list-style-type:none !important;
  display: block;
}
.discord-channel{
  font-weight:bold!important;
  list-style-type:none !important;
  padding-left:0;
}
.discord-userlist{
  padding-left:10px!important;
  list-style-type:none !important;
}
.discord-user{
  position:relative;
  white-space:nowrap;
  overflow:hidden;
}
.discord-user span{
  font-size:0.8em;
  opacity:0.5;
}
.discord-user-status{
  position:absolute;
  width:10px;
  height:10px;
  background-color:pink;
  border-radius:50%;
  border:solid thin #fff!important;
  border-color:#3a3a3a!important;
  top:14px;
  left:14px;
}
.discord-online{
  background-color:#43B581;
}
.discord-idle{
  background-color:#FAA61A;
}
.discord-avatar{
  border-radius:100%;
  width:24px;
  height:24px;
  border:solid 2px #fff!important;
  border-color:#3a3a3a!important;
  display:inline;
  margin-right:5px!important;
  vertical-align: middle;
}
.discord-allusers-toggle{
  cursor: default;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
.discord-users-online{
  font-size:0.75em!important;
  margin:10px 10px 0 0!important;
  text-align:right;
}
.discord-join{
  position:relative;
  width:100%;
  height:30px;
  text-align: center;
  margin: 10px 0 -5px 0!important;
  line-height:30px!important;
  z-index:2;
  color: white;
  background-color: #2461b2;
}
.discord-join a{
  color:#fff;
  text-decoration: none;
}
.discord-join:hover{
  background-color:#1b4a88;
}

.discord-tree{
	height:330px;
	overflow:auto;
}

</style>

<div class="container mar-top">
	<div class="row">
		<div class="heading text-center">
			<h1>Contact Us</h1>
			<?php if (isset($this->result)) { ?>
                <div class="opennotificationGreen" style="background-color:#66B45E; height: 40px" align="left" >
                    <p><font face="verdana" color="black">Your message has been sent!</font></p>
                </div>
            <?php } ?>
			<p class="text-white">We want to here from you. Choose from the contact options below</p>
		</div>
	</div>
</div>
  
<div class="container margin-40">
    <div class="row">
		<div class="well bg-image-1">
			<div class="tab-content">
				<div class="tab-pane fade in active">
					<div class="row col-container">
						<div class="col bg-image-2 download">
							<h4 class="m-top-lg text-white text-uppercase">Send Message Now</h4>
                  
							<form class="contactusform" method="post">
								<div class="modal-body">
                        
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										<select required name="topic" class="form-control input-bg-black">
											<option value="">select</option>
											<option value="Account Restrictions"> Account Restrictions</option>
											<option value="Affiliate Inquiries">Affiliate Inquiries</option>
											<option value="Bonus Issues">Bonus Issues</option>
											<option value="Cash Out Problems">Cash Out Problems</option>
											<option value="Contest Problems">Contest Problems</option>
											<option value="Depositing Problems">Depositing Problems</option>
											<option value="Login Problems">Login Problems</option>
											<option value="My Account">My Account</option>
											<option value="Other">Other</option>
											<option value="Press">Press</option>
											<option value="Suggestions">Suggestions</option>
											<option value="Technical Problems">Technical Problems</option>
										</select>
									</div>
									
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										<input type="text" class="form-control input-bg-black" value="<?php echo (isset($this->session->storage->userName))?$this->session->storage->userName:''; ?>" <?php  if (isset($this->session->storage->userName)) { echo "readonly"; } ?> name="username" placeholder="Username">
									</div>
                          
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										<input type="text" class="form-control input-bg-black" value="<?php echo (isset($this->session->storage->email))?$this->session->storage->email:''; ?>" name="email" id="email" required="true" placeholder="Email" >
									</div>
									
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										 <input type="text" class="form-control input-bg-black" value="" name="subject" id="subject" required="true" placeholder="Enter Subject">
									</div>
                        
                      
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										<textarea required="true" rows="5" name="message" id="message" onkeyup="LimtCharacters(this, 2000, 'lblcount');" type="text" class="form-control input-bg-black" placeholder="Message"></textarea>
										 
										
									</div>
									
									<span class="block text-white text-right">Number of characters left <label id="lblcount">2000</label></span>	
									
									<script src='https://www.google.com/recaptcha/api.js'></script>
									<div class="g-recaptcha input-group col-sm-12 col-md-10 col-md-offset-1 pd-15" data-sitekey="<?php echo $this->site_key; ?>"></div>
									<span style="color:red;"><?php if(!empty($this->errMsg)){ echo $this->errMsg;} ?></span></br>
									
									<div class="input-group col-sm-12 col-md-10 col-md-offset-1 pd-15">
										<button class="btn btn-blue">Submit</button>
									</div>
								</div>
							</form>
                      
                      
							<div class="min-h-200">
								<h4 class="m-top-lg text-white text-uppercase">You can also email us:</h4>
								<div class="padding-sm">
									<div class="row text-white">
										<div class="col-sm-12 m-bottom-sm">
											<div class="col-xs-8 col-xs-offset-2">
												<p class="font-medium-a"><span>Slack:</span> Coming Soon</p>
											</div>
										</div>
										
										<div class="col-sm-12 m-bottom-sm">
											<div class="col-xs-8 col-xs-offset-2">
												<p class="font-medium-a">
												<span>Email:</span> <a href="mailto:support@draftdaily.com" class="bold text-blue">support@draftdaily.com</a></p>	
											</div>
										</div>
										
										<div class="col-sm-12 m-bottom-sm">
											<div class="col-xs-8 col-xs-offset-2">
												<p class="font-medium-a"><span>Twitter:</span>@DraftLikeABoss</p>
											</div>
										</div>
										
									</div>
								</div>
							</div>        
						</div>

						<div class="col bg-image-2 download">
							<div class="row mr-15-right-left">
								<div class="black-transparent min-h-400">
									<h4 class="m-top-lg text-white text-uppercase">Live Support Chat With Us:</h4>

									<div class="padding-sm">
										<div class="row text-white">
											<div class="col-sm-12 m-bottom-sm">
												<div class="discord-widget"></div>
											</div>
										</div>
									</div>
								</div>
                            

								<div class="max-h-200">
									<h4 class="m-top-lg text-white text-uppercase">Support Hours:</h4>
									<h4 class="text-white paddingTB-sm paddingLR-lg"> </h4>
									<div class="padding-sm">
										<div class="row text-white">
											<div class="col-sm-12 m-bottom-sm">
												<div class="col-xs-8 col-xs-offset-2">
												<p class="font-medium-a">Monday-Friday  9:00AM-5:00PM EST</p>
												</div>
											</div>
																				
											<div class="col-sm-12 m-bottom-sm">
												<div class="col-xs-8 col-xs-offset-2">
												<p class="font-medium-a">Saturday&amp;Sunday 11:00AM-5:00PM EST</p>
												</div>
											</div>
											
											<br>
											
											<div class="col-sm-12 m-bottom-sm">
												<div class="col-xs-8 col-xs-offset-2">
																							
												<p class="font-medium-a"><a href="/support" class="bold text-blue">Draftdaily Support Team</a></p>
												</div>
											</div>
											
										</div>
									</div>
								</div>

							</div>
              
						</div>
					</div>
            
				</div>
			</div>
		</div>
	</div>
</div>
    
	
<?php if (isset($this->settings)) { ?>
    <script>
        $('.opennotificationGreen').fadeIn("slow");
        $('.opennotificationGreen').css('display', 'block');

        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        }, 3000);

    </script>    
<?php } ?>

<script type="text/javascript" src="https://cdn.jsdelivr.net/discord-widget/latest/discord-widget.min.js"></script>
<script type="text/javascript">
	discordWidget.init({
		serverId: '362315238734954496',
		title: 'DraftDaily Support Room',
		join: true,
		alphabetical: false,
		theme: 'dark',
		hideChannels: ['Channel Name 1', 'Channel Name 2'],
		showAllUsers: true,
		allUsersDefaultState: true,
		showNick: false
	});
	discordWidget.render();
</script>
<script>
    function LimtCharacters(txtMsg, CharLength, indicator) {
        chars = txtMsg.value.length;
        document.getElementById(indicator).innerHTML = CharLength - chars;
        if (chars > CharLength) {
            txtMsg.value = txtMsg.value.substring(0, CharLength);
        }
    }
</script>
<script>

    $(document).ready(function() {
		
		
        $('.discord-join a').html('Connect With Us');
        $('.contactusform').validate({
            rules: {
                topic: {
                    required: true
                },
                username: {
                    required: true

                },
                email: {
                    required: true,
                    email: true
                },
                message: {
                    required: true
                }

            },
            messages: {
                topic: {
                    required: "Please select a topic"
                },
                username: {
                    required: "Username is required Field"

                },
                email: {
                    required: "Email_id is Required",
                    email: "Please enter a valid email"
                },
                message: {
                    required: "Please enter desired message."
                }

            }

        });
    });
</script>