
<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
	$('#usertable').dataTable( {
		columnDefs: [ {
			targets: [ 0 ],
			orderData: [ 0, 1 ]
		}, {
			targets: [ 1 ],
			orderData: [ 1, 0 ]
		}, {
			targets: [ 4 ],
			orderData: [ 4, 0 ]
		} ]
	} );
} );

</script>
<div id="content">
	<h4>User Details</h4>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget">
		
		<!-- Widget heading -->
		<div class="widget-head">
			<h4 class="heading">User Manage</h4>
		</div>
		<!-- // Widget heading END -->
		
		<div class="widget-body">
		
			<!-- Table -->
			<table id="usertable" class="dynamicTable table table-striped table-bordered table-condensed">
			
				<!-- Table heading -->
				<thead>
					<tr>
						<th>No</th>
                                                <th>Firstname</th>
                                                <th>Lastname</th>
						<th>Username</th>
						<th>Email</th>
						<th class="center">Country</th>
						<th class="center">State</th>
                                                <th class="center">Status</th>
                                                <th class="center">Action</th>
                                                <th class="center">Edit / Delete</th>
					</tr>
				</thead>
				<!-- // Table heading END -->
				
				<!-- Table body -->
				<tbody>				
					<!-- Table row -->
                                        <?php  if(isset($this->users)): $row = 0; foreach($this->users as $userDetails): $row ++;?>
					<tr class="gradeA">
						<td><?php echo $row; ?></td>
                                                <td><?php if(isset($userDetails['fname'])) { echo $userDetails['fname']; }else{ echo "N/A"; } ?></td>
                                                <td><?php if(isset($userDetails['lname'])) { echo $userDetails['lname']; }else{ echo "N/A"; } ?></td>
						<td><?php echo $userDetails['user_name']; ?></td>
						<td><?php echo $userDetails['email']; ?></td>
						<td class="center"><?php echo $userDetails['country_name']; ?></td>
						<td class="center"><?php echo $userDetails['name']; ?></td>
                                                <?php if($userDetails['status']==1): ?>
                                                <td id="activeuser_<?php echo $userDetails['user_id']; ?>" class="center js-sortable-handle useractive">Active</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($userDetails['user_id'])): echo "users_" . $userDetails['user_id'];endif;?>" class="usersdeactive">
                                                <span id="activeclass_<?php echo $userDetails['user_id']; ?>" class="label label-block label-inverse">Deactivate</span></a></td>
                                                  <?php  else: ?>
                                                <td id="activeuser_<?php echo $userDetails['user_id']; ?>" class="center js-sortable-handle userdeactive">Suspended</td>
                                                <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($userDetails['user_id'])): echo "users_" . $userDetails['user_id']; endif;?>" class="usersactive">
                                                <span id="activeclass_<?php echo $userDetails['user_id']; ?>"  class="label label-block label-primary">Activate</span></a></td>
                                                <?php endif;?> 
                                                <td class="center">
                                                <a  href="edit-user/<?php echo $userDetails['user_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>
                                                <a  href="#" id="<?php  echo "userdelete_" . $userDetails['user_id'];  ?>" class="btn-action glyphicons remove_2 btn-danger-user"><i></i></a>
                                                </td>
					</tr>
                                          <?php endforeach;  endif; ?>
					<!-- // Table row END -->
					
					
					
				</tbody>
				<!-- // Table body END -->
				
			</table>
			<!-- // Table END -->
			
		</div>
	</div>
</div>	
</div>
<script>
    $('#menu_components').removeClass('collapse').addClass('in collapse');
    $('#user_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons user active');
    $('#user_details_menu').addClass('active');    
</script>
