<div id="content">
    <h4>User Account Details</h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading">Account Manage</h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">

                <!-- Table -->
                <table cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th>User Name</th>                            
                            <th>Balance Amount</th>
                            <th>FPP</th>                            
                            <th>Bonus Amount</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                       <?php if(isset($this->userAccountDetails)): foreach ($this->userAccountDetails as $accountDetails): ?>
                        <!-- Table row -->
                        <?php if($accountDetails['user_name']!='') {?>
                           
                            <td><?php echo $accountDetails['user_name']; ?></td>                            
                            <td><?php echo $accountDetails['balance_amt']; ?></td>
                            <td><?php echo $accountDetails['fpp']; ?></td>                            
                            <td ><?php echo $accountDetails['bonus_amt']; ?></td>
                            <td>
                                <a href="/admin/edit-account-details/<?php echo $accountDetails['user_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>
                                <?php
                            } ?>
                            </td>
                        </tr>
                        <!-- // Table row END -->
                        <?php endforeach; endif; ?>

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>

<script>
    $('#menu_components').removeClass('collapse').addClass('in collapse');
    $('#user_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons user active');
    $('#user_account_details_menu').addClass('active');    
</script>   

