<section class="background-bg">
    <div class="container">
        <div class="panel panel-main">
            <div class="panel-heading">
                <h3 class="font-ste-regular">TRANSACTION STATUS</h3>
            </div>
     
            <div class="panel-body">
                <div class="row">
                  <div class="col-md-12">
                        <div class="black-grad subtitle border-bot-blue5 text-center">
                            <h5 class="font-ste-regular">
                                
                                <strong>"Congratulations, We have received your payment 
                                    <?php if(isset($this->amount)){
                                        echo "of $".$this->amount;
                                    } ?>
                                    "</strong> 
                                <br>You are now ready to Draft!" The funds will be added to your balance within the next minute.<br> 
                                Click here to view your account
                            <br><br>
                            </h5><a href="/account"><button class="btn btn-success">My Account</button></a>
                        </div>
                        <div class="borderLRB">
                            <div class="row"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>