<div class="container mar-top">
		<div class="row">
			<div class="heading text-center">
				<h1>FREQUENTLY ASKED QUESTIONS</h1>
			</div>
		</div>
	</div>

	<div class="container margin-40">
		<div class="row">
			<div class="well bg-image-1">
				<div class="bg-image-2">
					<div class="bs-example">
						<div class="row">
							<div class="col-md-12">
								<ul class="nav nav-tabs pull-right" id="myTab">
									<li class="active"> <a  class="btn-success btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-A">BASICS</a></li>
									<li><a class="btn-success btn-success-a btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-B">ACCOUNT MANAGEMENT</a></li>
									<li><a class="btn-success btn-success-a btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-C">DEPOSITS, WITHDRWALS & BONUSES</a></li>
									<li><a class="btn-success  btn-success-a btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-D">GAMEPLAY/PRIZES</a></li>
									<li><a class="btn-success btn-success-a btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-E">REFER A FRIEND</a></li>
									<li><a class="btn-success btn-success-a btn-lg-lg-a btn3d text-uppercase" data-toggle="tab" href="#tab-F">CONTACT US</a></li>
								</ul>
							</div>
						</div>
			
						<div class="tab-content" id="myTabContent">			
							<div id="tab-A" class="tab-pane fade in active">
								<div class="row mr-15-right-left">
									<div class="padding-sm borderLRB">
										
										<h4 class="margin-20">What Is Draftdaily?</h4>
										<p class="font-medium-a">We offer Daily and Weekly Fantasy Sports contests in all of the four major sports (MLB, NHL, NFL, NBA). Our 1 day leagues contests are a much shorter duration than the traditional season-long leagues and require no team management after the draft. Our salary cap draft format takes just minutes to complete, unlike the hours-long snake drafts in traditional leagues. We offer new contests every day of the season, and our winners are crowned nightly. Payouts happen immediately after the games - no more waiting until the end of the season to collect winnings!</p>
										
										<h4 class="margin-20">Is Playing On Draftdaily Legal?</h4>
										<p class="font-medium-a">We are a skill games company, and all of our contests are operated 100% legally. We require our users to be 18 years of age or older (19 in Alabama and Nebraska).</p>
										
										<h4 class="margin-20">What Types of Contests Do you Offer?</h4>
										<div class="clearfix"></div>
										<p class="font-medium-a margin-10px">• GPP (Guaranteed Prize Pool) Contests – GPPs are contests that payout the entire prize pool, regardless if the contest fills or not.<br>
										•&nbsp;Head-to-Head- Winner takes all in these one-on-one contests.<br>
										•&nbsp;Leagues- Play against two or more opponents at a time in smaller field contests.<br>
										•&nbsp;50/50’s – Teams finishing in the top-half of the field win DFSCoins no matter the number of entries.<br>
										•&nbsp;Qualifier Contests – Win tickets that can be used for free entry into a higher stakes contest<br>
										GPP (Guaranteed Prize Pool) Contests – GPPs are contests that payout the entire prize pool, regardless if the contest fills or not.<br>
										•&nbsp;Multipliers- Great way for a bankroll boost! Win 3x TO 10x your entry fee in these contests.<br>
										•&nbsp;Steps- Advance at each step by winning a ticket to the next level. Jump in at Step 1 for just 2.00 and work your way to Step 4 to win!<br>
										•&nbsp;Beginner- Play against other beginners.<br>
										•&nbsp;Freeroll Contests – These contests are free to enter and any winnings will be paid with Entry Tickets or DFSCoins</p>
										
										<p class="font-medium-a margin-10px">Why Should I Choose Draftdaily?</p>
										<p class="font-medium-a">DraftDaily offers the most aggressive lineup of FREE contests with in Fantasy Sports. All of our contests are easy to enter, right off the home page. All of our games are daily (or weekly in NFL), which means you can play today and win today. Unlike full season leagues, you're never out of contention – every day starts fresh at DraftDaily.</p>
										
										<h4 class="margin-20">What is a Salary Cap Draft?</h4>
										
										<p class="font-medium-a">Each professional athlete available to draft in our leagues has a salary, and you have a fixed $55,000 budget to spend. You select a full roster of players while staying under the Salary Cap. Salary Cap drafting takes just minutes to complete, unlike the hours-long snake drafts in traditional leagues.</p>
									</div>
								</div>
							</div>
             
							<div id="tab-B" class="tab-pane fade">
								<div class="row mr-15-right-left">
									<div class="padding-sm borderLRB">
										<h4 class="margin-20">How Do I Create An Account? </h4>
										<p  class="font-medium-a">To create an account, you just need to create a username and password. Click here to get started. </p>
										<h4 class="margin-20">How Do I Find My Username?</h4>
										
										<ul class="how-to-play">
											<li><span  class="font-medium-a">Click Login at the top-right of the DraftDaily home page</span></li>
											<li><span  class="font-medium-a">Enter your email and password in the appropriate fields. Press Submit.</span></li>
											<li><span  class="font-medium-a">Your Username will be shown in the top-right corner of the page.</span></li>
										</ul>
										
										<h4 class="margin-20">Can I Change My Username? </h4>
										<p class="font-medium-a">Generally, we do not change usernames, though we treat each request individually. Let us know the specific details of your request and we will get back to you promptly.</p>
										<h4 class="margin-20">How Do I Reset My Password? </h4>
										
										<ul class="how-to-play">
											<li <span  class="font-medium-a">Click Login at the top-right of the DraftDailyhomepage
											</li>
											</li>
											<li> <span  class="font-medium-a">Click Forgot your password?</span></li>
											<li> <span  class="font-medium-a">Enter your email and click Submit.</span></li>
											<li> <span  class="font-medium-a">We will automatically send you an email with a link allowing you to change that password.</span></li>
										</ul>
										
									</div>
								</div>
							</div>
             
							<div id="tab-C" class="tab-pane fade">
								<div class="padding-sm borderLRB">
									<h4 class="margin-20">What Can I Use To Deposit?</h4>
									<ul class="how-to-play">
										<li><span class="font-medium-a">You will need to purchase DFSCoins to play.</span></li>
									</ul>
									
									<h4 class="margin-20">Where can I get DFSCoins?</h4>
									
									<ul class="how-to-play">
										<li><span class="font-medium-a"> We will be releasing DFSCoins very soon, email us for futher questions <a style="color:#5e8f03;" href="mailto:support@draftdaily.com"> support@draftdaily.com </a>:</span></li>
									</ul>
									
									<h4 class="margin-20">How Do I Withdraw My Winnings? </h4>
									<p class="font-medium-a"> Withdrawal is an available option on your My Account page. We think withdrawals should be as easy and as fast as deposits. As soon as we have processed your request, you will receive email confirmation.</p>
									
									<h4 class="margin-20">What Is Your Withdrawal Policy? </h4>
									<p class="font-medium-a">Bonus coins are not eligible for withdrawal you must first trade them for FPP.</p>
									
									<h4 class="margin-20">How Long Do Withdrawals Take? </h4>
									<p class="font-medium-a">Our accounting department processes withdrawals Monday-Friday from 9a to 5p. Once our accounting department processes your withdrawal request, it typically takes anywhere from 30 seconds to 2 minutes for your funds to appear in your DFSCoin Wallet.</p>
									
									<h4 class="margin-20">How Do I Get My Deposit Bonus?</h4>
									<p class="font-medium-a"> You can convert Deposit Bonuses to playable funds by exchanging them for FPP (Frequent Player Points). FPP is earned every time you enter a paid contest at the rate of 4 FPP per DFSCoin. </p>
									<br>
									
									<p class="font-medium-a"> **Deposit bonuses NEVER EXPIRE</p>
									
									<h4>What is a Frequent Player Point?</h4>
									
									<p class="font-medium-a">Frequent Player Points (FPPs) are points you earn upon the start of every paid contest you enter on DraftDaily.com, whether you win or lose. FPPs awarded vary per contest type (displayed on the Draft page) and are not earned for playing in FREE ENTRY games. The more contests you join and money you spend, the more FPPs you earn. </p>
									
									<h4 class="margin-20">Is there any Max Deposit limit? </h4>
									<p class="font-medium-a">No, However its recomended to keep large amounts of DFSCoins in your downloadable DFSCoin Wallet for your own security</p>
								</div>
							</div>
             
							<div id="tab-D" class="tab-pane fade">
								<div class="padding-sm borderLRB">
									
									<h4 class="margin-20">How Do Steps Contests Work?</h4>
									<p class="font-medium-a">Steps tournaments are a 4-level series of contests with continually higher buy-ins, peaking with huge prizes at the last step. For more information, see the Steps Tourney page. </p>
									
									<h4>Can I Withdraw An Entry From A Contest? </h4>
									<ul class="how-to-play">
										<li><span class="font-medium-a"> Users may unregister from unfilled Head to Head or League contests at any time.</span></li>
										<li> <span class="font-medium-a">Users may unregister from Guaranteed games until 15 minutes before start time.</span></li>
										<li><span class="font-medium-a"> Users may NOT unregister from a filled Head to Head contest.</span></li>
										<li> <span class="font-medium-a">Users may NOT unregister from a filled league games.</span></li>
									</ul>
									
									<h4 class="margin-20">How Do I Limit The Number of Contests Another Player Can Join From My H2H Challenges? </h4>
									<p class="font-medium-a">Use the limit selector on the Create Head-to-Head Challenge popup to limit the number of times a player can accept your challenges of that type (Sport, time and entry fee). For example, if you create 5 challenges and set the limiter to 1, all five challenges will be against different users, assuming all five challenges are accepted. Conversely, if you create 5 challenges and set the limiter to unlimited, you could end up playing the same user in all five challenges, assuming one user accepted all five challenges. </p>
									
									<h4 class="margin-20">What Happens If I Enter A Multi-Entry Contest And Win In Multiple Places? </h4>
									<p class="font-medium-a">You will receive your winnings for each spot that places in the contest. </p>
								
									<h4 class="margin-20">What Happens If A Real-Life Game Is Cancelled/Delayed/Postponed? </h4>
									<p class="font-medium-a">Players lock at the scheduled start time of their game, regardless of when the delay is announced or whether it is eventually postponed to a later date. You will continue to have the ability to swap out players before their respective scheduled game start time. </p>
									
									<h4 class="margin-20">What Does It Mean If I Win A Ticket? </h4>
									<p class="font-medium-a"> Entry tickets serve as a free entry into a specific contest. You can receive entry tickets by winning them in specific DraftDaily qualifier contests. Upon submitting your lineup into that ticket specific contest, your ticket will be automatically redeemed as way of entry. </p>
									
									<h4 class="margin-20">What If I Have Unredeemed Tickets For A Contest That Has Passed? </h4>
									<p class="font-medium-a"> If the contest in question did not fill, your unredeemed tickets will be voided and no refund will be issued. </p>
									
									<h4 class="margin-20">What Happens If Two Users Tie In A Contest? </h4>
									<p class="font-medium-a">If there is a tie at the end of the contest, users included in the tie will evenly split the related prize pool. For example, if two users tie for 1st place, and 1st place pays 20,000 and 2nd place pays 10,000 we add the combine places then split that among the tied parties. Each would receive 15,000.

									*If the prize is a ticket, the value of the ticket (or tickets) will be split.</p>
									
									<h4 class="margin-20">What Happens If One Of My Players Is Injured/Is Out/Doesn't Play? </h4>
									<p class="font-medium-a">In the event that one of your players does not play, that player will receive 0 points. The player may be swapped up until the scheduled start time of his game. </p>
									
									<h4 class="margin-20">Are The Contests Free To Play?</h4>
									<p class="font-medium-a">We have freeroll contests, EVERY DAY, that are completely free to play and you can win DFSCoins if your team performs well. There is no deposit required to play. You can just create an account and enter. We also offer a wide variety of games where you enter for a DFSCoin buy-in and can win prizes. </p>
									
									<h4 class="margin-20"> How Are Contests Scored?</h4>
									<p class="font-medium-a">Our contests have a points-based scoring format. Please see the specific sport for details:</p>
									<ul class="how-to-play">
										<li><span class="font-medium-a">MLB</span></li>
										<li><span class="font-medium-a">NFL</span></li>
										<li><span class="font-medium-a">NHL</span></li>
										<li><span class="font-medium-a">NBA</span></li>
									</ul>
									
									<h4>How Do I Enter Contests? </h4>
									<p class="font-medium-a">DraftDaily offers a variety of contests, all available to enter directly from our home page. Choose your game and buy-in preference, and select the game of your choice to enter. </p>
								</div>
							</div>

							<div id="tab-E" class="tab-pane fade">
								<div class="row">
									<div class="padding-sm borderLRB">
										<h4 class="margin-20">How and When Will I Get Paid? </h4>
										<p class="font-medium-a">Payments are deposited directly into your on site wallet. These deposits cannot be withdrawn as DFSCoins to your offline DFSCoin Wallet or to any participating crypto currency exchange, but can be used to pay for entry into any of our contests or tournament </p>

										<h4 class="margin-20">How Do You Determine How Much I Have Earned? </h4>

										<p class="font-medium-a">Every time you send a referral to our site by having them click YOUR link, and they play a deposit game, you earn a share of the cost of their entry. For 2017, you can earn 35% on every referral. </p>

										<h4 class="margin-20">How Much Money Can I Make? </h4>

										<p class="font-medium-a">The amount you can earn depends entirely on the number of players you send our way. Please note that the income level can vary widely from one person to another. Simply put, the more you send customers our way and encourage referrals to deposit and play, the more you can earn. There is no cap on the number of players you can recruit, and therefore no limit to the amount of money you can make.  </p>


										<h4 class="margin-20">How Do I Keep Track of How Much I've Earned?</h4>

										<p class="font-medium-a">All you have to do is use your standard DraftDaily username and password to log in to the site, and then click Refer A Friend right from our homepage. Once you reach the Refer A Friend page, all the information you'll need is available at a glance. Not only can you easily send new referrals from this page, you can also easily track your performance. You will see your current rate, see which referrals have signed up and which have not so you know who needs another nudge to get in on the action.
										Your lifetime performance is also recorded, and can be easily accessed through the My Accounts page. All of the referral income you have earned will be displayed under Payment History.</p>
									</div>
								</div>
							</div>

							<div id="tab-F" class="tab-pane fade">
								<div class="padding-sm borderLRB">
									<p class="font-medium-a margin-20">To contact a team member, please email
										<a style="color:#5e8f03;" href="mailto:support@draftdaily.com">support@draftdaily.com </a>and we will get back to you quickly.
									</p>
									
									<h4 class=" margin-20">Customer Support Business hours</h4>
									<ul id="ul" class="how-to-play">
										<li><span class="font-medium-a">Sunday - 11am-7pm EST</span></li>
										<li><span class="font-medium-a">Monday - 9am-11pm EST</span></li>
										<li><span class="font-medium-a">Tuesday - 9am-11pm EST</span></li>
										<li><span class="font-medium-a">Wednesday - 9am-11pm EST</span></li>
										<li><span class="font-medium-a">Thursday - 9am-11pm EST</span></li>
										<li><span class="font-medium-a">Friday - 9am-11pm EST</span></li>
										<li><span class="font-medium-a">Saturday - 11am-7pm EST</span></li>
									</ul>
								</div>
							</div>                            
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>