	<div class="container mar-top">
		<div class="row">
			<div class="heading text-center">
				<h1>How To play</h1>
			</div>
		</div>
	</div>
  
	<div class="container margin-40">
		<div class="row">
			<div class="well bg-image-1">
				<div class="bg-image-2">
					<div class="row">
						<div class="padding-md m-top-sm">
							<h3>The Basics</h3>
							
							<h4>Game On</h4>
							
							<ul class="how-to-play">
								<li><span class="font-medium-a">DraftDaily.com hosts daily and weekly fantasy sports contests in a variety of formats to suit DFS Rookies, Veterans and All Pro fantasy owners.</span></li>
								
								<li><span class="font-medium-a">We host free to enter contests, known as “freeroll games” as well as buy-in contests for real prizes.</span></li>
								
								<li><span class="font-medium-a">Guaranteed fantasy sports contest have a Guaranteed prize pool even if the contest is not filled when it begins.</span></li>
								
								<li><span class="font-medium-a">All other contests are non-guaranteed and will be cancelled if there are not enough teams to fill the league when the live games begin, the buy-in amount will be refunded.</span></li>
								
								<li><span class="font-medium-a">Decide whether you want to play fantasy NFL, NBA, MLB or NHL. Or test your skills in all four. Click on the "Enter" button to enter that contest and draft a team.</span></li>
							</ul>
							
							<h4>DRAFT LIKE A BOSS!</h4>
							<ul class="how-to-play">
								<li><span class="font-medium-a">Congratulations you’re now a Fantasy Team Owner and on your way to fame and fortune… well maybe not, but at the least a really good time. Each fantasy team owner has a 55,000 DFS salary cap to build their fantasy team.</span></li>
								<li><span class="font-medium-a">Draft players to your team before the current day's games; just remember to stay under the salary cap and pick player who you think will perform well during the game.</span></li>
								<li><span class="font-medium-a">Player salaries are based on their real game performance and stats, and are not related to the player's real team salary.</span></li>
								<li><span class="font-medium-a">Now that you’ve drafted your fantasy team and all the positions have been filled, you’re ready to play and even join other contests with the players you just drafted or make another lineup.</span></li>
								<li><span class="font-medium-a">Having second thoughts about your dream team? Don’t worry, team owners can change their lineups at any time before the contest starts.</span></li>
							</ul>
							
							<h4>DRAFT LIKE A BOSS!</h4>
							
							<ul class="how-to-play">
								<li><span class="font-medium-a">By clicking on the "My Contests" tab near the top of the webpage you can watch as your players rack up stats and score points.</span></li>
								<li><span class="font-medium-a">Go to the "Live Contests" area and click view to watch the contests you have entered in progress.</span></li>
								<li><span class="font-medium-a">Team owners can also see how the team they drafted stacks up against the competition.</span></li>
							</ul>
							
							<h4>WIN BIG PRIZES!</h4>
							<ul class="how-to-play">
								<li><span class="font-medium-a">If you entered a paid contest you win the amount determined by the prize structure for that contest from the prize pool.</span></li>
								<li><span class="font-medium-a">The DFSCoins you win will automatically be credited to your account so you can use it to enter more contests!</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
 