<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
	$('#offersmg').dataTable( {
		columnDefs: [ {
			targets: [ 0 ],
			orderData: [ 0, 1 ]
		}, {
			targets: [ 1 ],
			orderData: [ 1, 0 ]
		}, {
			targets: [ 4 ],
			orderData: [ 4, 0 ]
		} ]
	} );
} );

</script>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>

        <link rel="stylesheet" type="text/css" href="css/local.css" />

        <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    </head>
    <body>

        <div id="wrapper">

            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index">Admin Panel</a>
                </div>



                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li class="dropdown messages-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">2</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">2 New Messages</li>
                            <li class="message-preview">
                                <a href="#">
                                    <span class="avatar"><i class="fa fa-bell"></i></span>
                                    <span class="message">Security alert</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li class="message-preview">
                                <a href="#">
                                    <span class="avatar"><i class="fa fa-bell"></i></span>
                                    <span class="message">Security alert</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Go to Inbox <span class="badge">2</span></a></li>
                        </ul>
                    </li>
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Steve Miller<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>

                        </ul>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <form class="navbar-search">
                            <input type="text" placeholder="Search" class="form-control">
                        </form>
                    </li>
                </ul>
        </div>
    </nav>

    <div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h1>Dashboard <small>Statistics and more</small></h1>
                <div class="alert alert-dismissable alert-warning">
                    <button data-dismiss="alert" class="close" type="button">×</button>
                    <h4>Warning!</h4>
                    <p>You have two new messages.
                    </p>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-md-8">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Visits Based on a 10 days data</h3>
                    </div>
                    <div class="panel-body">
                        <div id="shieldui-chart1"></div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-rss"></i> Feed</h3>
                    </div>
                    <div class="panel-body feed">
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-comment"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    <a href="#"></a> commented on <a href="#">What Makes Good Code Good</a>.
                                </div>
                                <div class="time pull-left">
                                    3 h
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-check"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    <a href="#">Merge request #42</a> has been approved by <a href="#">Jessica Lori</a>.
                                </div>
                                <div class="time pull-left">
                                    10 h
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-plus-square-o"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    New user <a href="#">Greg Wilson</a> registered.
                                </div>
                                <div class="time pull-left">
                                    Today
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-bolt"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    Server fail level raises above normal. <a href="#">See logs</a> for details.
                                </div>
                                <div class="time pull-left">
                                    Yesterday
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-archive"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    <a href="#">Database usage report</a> is ready.
                                </div>
                                <div class="time pull-left">
                                    Yesterday
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-shopping-cart"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    <a href="#">Order #233985</a> needs additional processing.
                                </div>
                                <div class="time pull-left">
                                    Wednesday
                                </div>
                            </div>
                        </section>
                        <section class="feed-item">
                            <div class="icon pull-left">
                                <i class="fa fa-arrow-down"></i>
                            </div>
                            <div class="feed-item-body">
                                <div class="text">
                                    <a href="#">Load more...</a>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Traffic Sources One month tracking </h3>
                    </div>
                    <div class="panel-body">
                        <div id="shieldui-grid1"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Logins per week</h3>
                    </div>
                    <div class="panel-body">
                        <div id="shieldui-chart2"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-magnet"></i> Server Overview</h3>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">

                <header>
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a data-toggle="tab" href="#stats">Users</a>
                        </li>
                        <li class="">
                            <a data-toggle="tab" href="#report">Favorites</a>
                        </li>
                        <li class="">
                            <a data-toggle="tab" href="#dropdown1">Commenters</a>
                        </li>
                    </ul>
                </header>
                <div class="body tab-content">
                    <div class="tab-pane clearfix active" id="stats">
                        <h5 class="tab-header"><i class="fa fa-calendar-o fa-2x"></i> Last logged-in users</h5>
                        <ul class="news-list">
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="position"></div>
                                    <div class="time"></div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="position"></div>
                                    <div class="time"></div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="position"></div>
                                    <div class="time"></div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="position"></div>
                                    <div class="time"></div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="position"></div>
                                    <div class="time"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-pane" id="report">
                        <h5 class="tab-header"><i class="fa fa-star fa-2x"></i> </h5>
                        <ul class="news-list news-list-no-hover">
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="options">
                                        <button class="btn btn-xs btn-success">
                                            <i class="fa fa-phone"></i>
                                            Call
                                        </button>
                                        <button class="btn btn-xs btn-warning">
                                            <i class="fa fa-envelope-o"></i>
                                            Message
                                        </button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="options">
                                        <button class="btn btn-xs btn-success">
                                            <i class="fa fa-phone"></i>
                                            Call
                                        </button>
                                        <button class="btn btn-xs btn-warning">
                                            <i class="fa fa-envelope-o"></i>
                                            Message
                                        </button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="options">
                                        <button class="btn btn-xs btn-success">
                                            <i class="fa fa-phone"></i>
                                            Call
                                        </button>
                                        <button class="btn btn-xs btn-warning">
                                            <i class="fa fa-envelope-o"></i>
                                            Message
                                        </button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="options">
                                        <button class="btn btn-xs btn-success">
                                            <i class="fa fa-phone"></i>
                                            Call
                                        </button>
                                        <button class="btn btn-xs btn-warning">
                                            <i class="fa fa-envelope-o"></i>
                                            Message
                                        </button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="options">
                                        <button class="btn btn-xs btn-success">
                                            <i class="fa fa-phone"></i>
                                            Call
                                        </button>
                                        <button class="btn btn-xs btn-warning">
                                            <i class="fa fa-envelope-o"></i>
                                            Message
                                        </button>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-pane" id="dropdown1">
                        <h5 class="tab-header"><i class="fa fa-comments fa-2x"></i> Top Commenters</h5>
                        <ul class="news-list">
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="comment">

                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="comment">

                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="comment">

                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="comment">

                                    </div>
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-user fa-4x pull-left"></i>
                                <div class="news-item-info">
                                    <div class="name"><a href="#"></a></div>
                                    <div class="comment">

                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
<!-- /#wrapper -->
<script type="text/javascript">
    jQuery(function ($) {
        var performance = [12, 43, 34, 22, 12, 33, 4, 17, 22, 34, 54, 67],
        visits = [123, 323, 443, 32],
        traffic = [
            {
                Source: "Direct", Amount: 323, Change: 53, Percent: 23, Target: 600
            },
            {
                Source: "Refer", Amount: 345, Change: 34, Percent: 45, Target: 567
            },
            {
                Source: "Social", Amount: 567, Change: 67, Percent: 23, Target: 456
            },
            {
                Source: "Search", Amount: 234, Change: 23, Percent: 56, Target: 890
            },
            {
                Source: "Internal", Amount: 111, Change: 78, Percent: 12, Target: 345
            }];


        $("#shieldui-chart1").shieldChart({
            theme: "dark",

            primaryHeader: {
                text: "Visitors"
            },
            exportOptions: {
                image: false,
                print: false
            },
            dataSeries: [{
                    seriesType: "area",
                    collectionAlias: "Q Data",
                    data: performance
                }]
        });

        $("#shieldui-chart2").shieldChart({
            theme: "dark",
            primaryHeader: {
                text: "Traffic Per week"
            },
            exportOptions: {
                image: false,
                print: false
            },
            dataSeries: [{
                    seriesType: "pie",
                    collectionAlias: "traffic",
                    data: visits
                }]
        });

        $("#shieldui-grid1").shieldGrid({
            dataSource: {
                data: traffic
            },
            sorting: {
                multiple: true
            },
            rowHover: false,
            paging: false,
            columns: [
                { field: "Source", width: "170px", title: "Source" },
                { field: "Amount", title: "Amount" },                
                { field: "Percent", title: "Percent", format: "{0} %" },
                { field: "Target", title: "Target" },
            ]
        });            
    });        
</script>
</body>
</html>
