<div class="opennotificationGreen" style="z-index: 99;">
<span class="notification_msgGreen">Changes saved successfully.</span>
</div>
<div id="content">
	<h3>Edit Ticket</h3>
<div class="innerLR">

	<!-- Widget -->
	<div class="widget widget-tabs border-bottom-none">
	
		<!-- Widget heading -->
		<div class="widget-head">
			<ul>
				<li class="active"><a class="glyphicons edit" href="#account-details" data-toggle="tab"><i></i>Manage Ticket</a></li>
<!--				<li><a class="glyphicons settings" href="#account-settings" data-toggle="tab"><i></i>Account settings</a></li>-->
			</ul>
		</div>
		<!-- // Widget heading END -->
		
		<div class="widget-body">
                    <form class="form-horizontal margin-none editticketform"  method="post">
				<div class="tab-content pad0">
				
					<!-- Tab content -->
					<div class="tab-pane active" id="account-details">
					
						<!-- Row -->
						<div class="row-fluid">
						
							<!-- Column -->
							<div class="span6">
                                                            
                                                                <!-- Group -->
								<div class="control-group">
									<label class="control-label">Ticket Contest</label>
									<div class="controls">
										<input readonly type="text" value="<?php echo $this->data['description']; ?>" class="span10" name="code"/>
									</div>
								</div>
								<!-- // Group END -->
                                                                <!-- Group -->
								<div class="control-group">
									<label class="control-label">Code</label>
									<div class="controls">
										<input readonly type="text" value="<?php echo $this->data['code']; ?>" class="span10" name="code"/>
									</div>
								</div>
								<!-- // Group END -->
                                                                
                                                                <!-- Group -->
								<div class="control-group">
									<label class="control-label">Selling</label>
									<div class="controls">
                                                                            <select class="span4" name="selling">
                                                                                <?php if($this->data['selling_status'] == '1'): ?>
                                                                                <option selected value="1">Yes </option>                                                                                
                                                                                <option  value="0">No</option>                                                                                
                                                                                <?php else: ?>
                                                                                <option  value="1">Yes </option>                                                                                
                                                                                <option selected  value="0">No</option>                                                                                
                                                                                <?php endif; ?>
                                                                            </select>										
										<!--<span class="btn-action single glyphicons circle_question_mark margin-none" data-toggle="tooltip" data-placement="top" data-original-title="Last name is mandatory"><i></i></span>-->
									</div>
								</div>
								<!-- // Group END -->
                                                                
								
								<!-- Group -->
								<div class="control-group">
									<label class="control-label">Status</label>
									<div class="controls">
                                                                            <select class="span4" name="status">
                                                                                <?php if($this->data['status'] == '1'): ?>
                                                                                <option selected value="1">Active </option>                                                                                
                                                                                <option  value="0">Deactive</option>                                                                                
                                                                                <?php else: ?>
                                                                                <option  value="1">Active </option>                                                                                
                                                                                <option selected  value="0">Deactive</option>                                                                                
                                                                                <?php endif; ?>
                                                                            </select>										
										<!--<span class="btn-action single glyphicons circle_question_mark margin-none" data-toggle="tooltip" data-placement="top" data-original-title="Last name is mandatory"><i></i></span>-->
									</div>
								</div>
								<!-- // Group END -->
                                                               

                                                        </div>
                                                        <div class="span6">
                                                            <!-- Group -->
								<div class="control-group">
									<label class="control-label">Valid From</label>
									<div class="controls">
										<input type="text" name="valid_from" id="datepicker1" value="<?php echo $this->data['valid_from']; ?>" class="span5" />
                                                                                 
                                                                        </div>
								</div>
								<!-- // Group END -->
                                                                <!-- Group -->
								<div class="control-group">
									<label class="control-label">Valid Upto</label>
									<div class="controls">
										<input type="text" name="valid_upto" id="datepicker" value="<?php echo $this->data['valid_upto']; ?>" class="span5" />
									</div>
								</div>
								<!-- // Group END -->
                                                                
                                                                <!-- Group -->
								<div class="control-group">
									<label class="control-label">FPP Amount</label>
									<div class="controls">
                                                                            <input type="text" name="fpp" id="fpp" value="<?php if(isset($this->data['fpp'])) { echo $this->data['fpp']; } ?>" class="span5" />
									</div>
								</div>
								<!-- // Group END -->
                                                               
                                                        </div>
						</div>
						<!-- // Row END -->
						
						<div class="separator line bottom"></div>
						
                                                <!-- Form actions -->
						<div class="form-actions" class="margin-none">
							 <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button></a>
                                                       <a href="/admin/ticket"> <button type="button" class="btn btn-icon btn-default glyphicons circle_remove"><i></i>Cancel</button></a> 
                                                             
						</div>
						<!-- // Form actions END -->
						
					</div>
					<!-- // Tab content END -->
					
				</div>
			</form>
		</div>
	</div>
	<!-- // Widget END -->
	
</div>	
</div>
<script>
    $('#menu_store').removeClass('collapse').addClass('in collapse');
    $('#store_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#tickets').addClass('active');    
</script>

<?php if(isset($this->success)) {?>
<!-- This script Displays the  notification when the user details are submitted on submit  -->
<script>  
        $('.opennotificationGreen').click(function()
        {
//            alert('ss');
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        });
    
        $('.opennotificationGreen').fadeIn("slow");             
        $('.opennotificationGreen').css('display','block');
        
        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 3000); 
           setTimeout(function() {   
          window.location.replace("/admin/ticket");   
        }, 3000); 
    </script>
    <?php }?>