      
      <div class="panel panel-default">
          <div class="panel-heading">Sign Up Now</div>
            <div class="panel-body">
                <div class="row">
                        <div class="col-md-4 sidebar">
                            
                            <form class="signupform" role="form" method="post">
                                

                                <div class="form-group signupgroup logingroup" >
                                  <label for="usernameinp">Username</label>
                                  <input type="text"  name="username" class="form-control" id="usernameinp" placeholder="Username">
                                 
                                </div>
                                <div class="radio">
                                    <label>
                                      <input type="radio" class="optionradio" name="optionsRadios" id="optionsRadios1" value="login" >
                                      Yes, I already have a password
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                      <input type="radio" class="optionradio" name="optionsRadios" id="optionsRadios2" value="signup" checked>
                                      No, I'm a new customer
                                    </label>
                                </div>
                                <div class="form-group signupgroup">
                                  <label for="emailinp">Email address</label>
                                  <input type="email" name="email" class="form-control" id="emailinp" placeholder="Email">
                                 
                                </div>
                                <div class="form-group signupgroup logingroup">
                                  <label for="passwordinp">Password</label>
                                  <input type="password" name="password" class="form-control" id="passwordinp" placeholder="Password">
                                 
                                </div>
                                <div class="form-group signupgroup">
                                  <label for="confirmpassword"> Confirm Password</label>
                                  <input type="password" name="confirmPassword" class="form-control" id="confirmpassword" placeholder="Password">
                                  
                                </div>
                                <div class="form-group signupgroup">
                                    <label for="countryinp">Country</label>
                                    <select name="countryoption" id="countryinp" class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                                <div class="form-group signupgroup">
                                    <label for="cityinp">City</label>
                                    <select name="cityoption" id="cityinp" class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                                
                                <div class="checkbox signupgroup">
                                  <label>
                                    <input type="checkbox" name="agreeterms"> I agree to the Terms of Use and the Privacy Policy.
                                  </label>
                                </div>
                                
                                <div class="checkbox signupgroup">
                                  <label>
                                    <input type="checkbox" name="ageconfirm"> I confirm that I am at least 18 years of age. Must be 19 years of age in Alabama and Nebraska.
                                  </label>
                                </div>
                                <button  type="submit" class="btn btn-default signupsubmit">Submit</button>
                              </form>

                            
                            
                            
                        </div>
                        <div class="col-md-8">
                            
                            <div class="right-style">
                                <h2>Why <?php echo $this->appSetting->title; ?>?</h2>
                                <ul>
                                    <li>Play FREE and Win Cash every day!</li>
                                    <li>Fast and easy to play - draft your team in just 2 minutes</li>
                                    <li>Play 1-on-1, or win more vs. a bigger pool of players (5-man, 10-man, or tournaments)</li>
                                    <li>Instant, secure deposits and easy withdrawals</li>
                                    <li>We are a US-based skill games company - our contests are operated 100% legally</li>
                                </ul>
                            </div>
                            
                        </div>
                </div>
      
            </div>
      </div>
