<div class="panel bordernone">
    <div class="panel-body">
        <img alt="Draft Off" src="/assets/images/logo-large@2x1.png" width="90" />
        <h2 class="text-center">Daily Fantasy Sports For Cash</h2>

        <div class="col-md-12">
            <div class="col-md-7 text-center">
                <div class="thumb_box" style=" padding: 0; width: 100%; color: #333;">  
                    <h3><i class="fa fa-star"></i>
                        First-Time Deposit Offer
                        <i class="fa fa-star"></i></h3>
                    <h4>FREE Entry to a Fantasy Contest – win real cash!</h4>
                    <h5>Plus, deposit now and we'll double your cash!</h5>
                    <br>
                    <?php if(isset($this->affuser)){ ?>
                    <a href="/login?showmodal=true" class="btn btn-black" data-toggle="modal" data-target="#loginModal" id="formvalidatorid">PLAY NOW >></a>
                    <?php }else{ ?>
                    <a href="/" class="btn btn-black" >PLAY NOW >></a>
                    <?php } ?>
                    <h6></h6>

                </div>

            </div>
            <div class="col-md-5 text-center">
               
            </div>

        </div>

        <div class="col-md-12 margint20">

            <div class="bs-docs-example">
                <ul class="nav nav-tabs width100" id="myTab">
                    <li class="active"><a data-toggle="tab" href="#aboutus">About Us</a></li>
                    <li class=""><a data-toggle="tab" href="#whydraftoff">Why Draftoff?</a></li>
                    <li class=""><a data-toggle="tab" href="#howtoplay">How To Play</a></li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div id="aboutus" class="tab-pane fade active in margint20">

                        <ul>

                            <li>Play free or paid contests and win real money!</li>
                            <li>Daily leagues - no season-long commitment.</li>
                            <li>DraftOff is skill based game and is 100% legal.</li>

                        </ul>

                    </div>
                    <div id="whydraftoff" class="tab-pane fade margint20">
                        <ul>
                            <li>Draftoff is a daily fantasy sports site where you can WIN real money.</li>
                            <li>Large variety of both free and paid contests in multiple game types.</li>
                            <li>Featured tournaments.</li>
                            <li>Daily leagues for fantasy football, fantasy baseball, fantasy basketball and fantasy hockey.</li>
                        </ul>

                    </div>
                    <div id="howtoplay" class="tab-pane fade">
                        <div class="row margint20">
                            <div class="col-md-1"></div>
                            <div class="col-md-2 text-center">
                                <h3>1</h3>
                                <h4>Sign Up Free</h4>
                                <p>Simply provide your email address to start playing daily fantasy sports for real money.</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <h3>2</h3>
                                <h4>Choose a Contest</h4>
                                <p>Free or paid entry, head to head or tournament, it's up to you.</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <h3>3</h3>
                                <h4>Draft Your Team</h4>
                                <p>Our easy to use site will have your team assembled in minutes.</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <h3>4</h3>
                                <h4>Watch Live</h4>
                                <p>Monitor the action live on your computer or mobile device.</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <h3>5</h3>
                                <h4>Win Cash</h4>
                                <p>Your account is credited as soon as the contest ends.</p>
                            </div>
                            <div class="col-md-1"></div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <div class="row bgblack margint20 pull-left width100">
           
        </div>
    </div>

</div>
