<div class="panel panel-default">
  <div class="panel-body">
      <div class="page-header">
         <h1><small>Sign Up</small></h1>
      </div>
      
      
      <div class="panel panel-default">
          <div class="panel-heading">Sign Up Now</div>
            <div class="panel-body">
                <div class="row">
                        <div class="col-md-4 sidebar">
                            
                            <form role="form">
                                

                                <div class="form-group">
                                  <label for="usernameinp">Username</label>
                                  <input type="text" class="form-control" id="usernameinp" placeholder="Username">
                                </div>
                                <div class="radio">
                                    <label>
                                      <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                                      Yes, I already have a password
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                      <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                      No, I'm a new customer
                                    </label>
                                </div>
                                <div class="form-group">
                                  <label for="emailinp">Email address</label>
                                  <input type="email" class="form-control" id="emailinp" placeholder="Email">
                                </div>
                                <div class="form-group">
                                  <label for="passwordinp">Password</label>
                                  <input type="password" class="form-control" id="passwordinp" placeholder="Password">
                                </div>
                                <div class="form-group">
                                  <label for="confirmpassword"> Confirm Password</label>
                                  <input type="password" class="form-control" id="confirmpassword" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <label for="countryinp">Country</label>
                                    <select id="countryinp" class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="cityinp">City</label>
                                    <select id="cityinp" class="form-control">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                                
                                <div class="checkbox">
                                  <label>
                                    <input type="checkbox"> I agree to the Terms of Use and the Privacy Policy.
                                  </label>
                                </div>
                                
                                <div class="checkbox">
                                  <label>
                                    <input type="checkbox"> I confirm that I am at least 18 years of age. Must be 19 years of age in Alabama and Nebraska.
                                  </label>
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                              </form>

                            
                            
                            
                        </div>
                        <div class="col-md-8">
                            
                            <div class="right-style">
                                <h2>Why DraftOff?</h2>
                                <ul>
                                    <li>Play FREE and Win Cash every day!</li>
                                    <li>Fast and easy to play - draft your team in just 2 minutes</li>
                                    <li>Play 1-on-1, or win more vs. a bigger pool of players (5-man, 10-man, or tournaments)</li>
                                    <li>Instant, secure deposits and easy withdrawals</li>
                                    <li>We are a US-based skill games company - our contests are operated 100% legally</li>
                                </ul>
                            </div>
                            
                        </div>
                </div>
      
            </div>
      </div>
      
      
     
      
  </div>
</div>


