<div class="container mar-top">	<div class="row">		<div class="heading text-center">			<div class="tab-content">				<div class="tab-pane fade in active" id="tab1a">					<h1 id="headerTitle">Reset password</h1>				</div>			</div>		</div>	</div></div>      <div class="container margin-40">
	<div class="panel panel-default" style="background-image:url(assets/images/baseball-background.jpg); background-repeat: no-repeat;background-size: cover;">
		<div class="panel-heading text-center" style="background-image: url(assets/images/header.png);background-position: initial;height: 45px;color:#1385fe;padding-left: 20px;font-size: 18px;font-weight: bold;"><b><?php echo (!empty($this->message))?$this->message:"Change Password";?></b></div>
		<div class="panel-body">
			<div class="row">				<?php if(isset($this->userData)){ ?>
				<div class="col-md-4 col-md-offset-4 sidebar">
					
					<form class="signupform" role="form" method="post" >
						<div class="form-group signupgroup logingroup" >
							<label for="passwordinp">Password</label>
							<input type="password" name="password" class="form-control" id="passwordinp" autocomplete="off" placeholder="Password">
						</div>                    
						<button  type="submit" class="btn-success btn-lg btn3d ">Change</button>						<a href="/"><button type="button" class="btn-submit btn-lg btn3d">Cancel</button></a>
					</form>
				</div>				<?php }else {  ?>				<div class="text-center">					Sorry, Something went wrong. Please Try after some time.									</div>				<?php } ?>
			</div>
		</div>
	</div></div>
