
<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
	$('#appusertable').dataTable( {
		columnDefs: [ {
			targets: [ 0 ],
			orderData: [ 0, 1 ]
		}, {
			targets: [ 1 ],
			orderData: [ 1, 0 ]
		}, {
			targets: [ 4 ],
			orderData: [ 4, 0 ]
		} ]
	} );
} );

</script>
<div id="content">
	<h4>App User Details</h4>
	<div class="innerLR">

		<!-- Widget -->
		<div class="widget">
			
			<!-- Widget heading -->
			<div class="widget-head">
				<h4 class="heading">App User Manage</h4>
			</div>
			<!-- // Widget heading END -->
			
			<div class="widget-body">
			
				<!-- Table -->
				<table id="appusertable" class="dynamicTable table table-striped table-bordered table-condensed">
				
					<!-- Table heading -->
					<thead>
						<tr>
							<th>No</th>
							<th>User Name</th>
							<th>Email</th>
							<th class="center">Status</th>
							<th class="center">Action</th>
						</tr>
					</thead>
					<!-- // Table heading END -->
					
					<!-- Table body -->
					<tbody>				
						<!-- Table row -->
						<?php  if(isset($this->appUserDetails)): $row = 0; foreach($this->appUserDetails as $userDetails): $row ++;?>
						<tr class="gradeA">
							<td><?php echo $row; ?></td>
							<td><?php if(isset($userDetails['name'])) { echo $userDetails['name']; }else{ echo "N/A"; } ?></td>
							<td><?php echo $userDetails['email']; ?></td>
							<td class="center"><?php echo ($userDetails['status']==1)?"<span style='color:green;'>Active</span>":"<span style='color:red;'>Inactive</span>";?></td>
							<td class="center">
								<a title="Edit" href="/admin/api-user/edit/<?php echo $userDetails['id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>&nbsp;
								<a title="App List" href="/admin/user/app-list/<?php echo $userDetails['id']; ?>" class="btn-action  btn-success glyphicons list"><i></i></a> 
							</td>
						</tr>
						<?php endforeach;  endif; ?>
						<!-- // Table row END -->
						
						
						
					</tbody> 
					<!-- // Table body END -->
					
				</table>
				<!-- // Table END -->
				
			</div>
		</div>
	</div>	
</div>
<script>
    $('#menu_api').removeClass('collapse').addClass('in collapse');
    $('#api_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons list active');
    $('#menu_api_1').addClass('active');    
</script>
