<div id="content">
	<div class="innerLR">
		<!-- Widget -->
		<!-- Widget -->

<div class="widget widget-tabs border-bottom-none">
	<!-- Widget heading -->

	<div class="widget-head">
		<ul>

			<li class="active"><a class="glyphicons edit" href="#account-details" data-toggle="tab"><i></i>Account details</a></li>
		</ul>
	</div>
	<!-- // Widget heading END -->
	<div class="widget-body">
		<form class="form-horizontal margin-none" action="" role="form" method="post">

			<div class="tab-content pad0">
				<!-- Tab content -->

				<div class="tab-pane active" id="account-details">
					<!-- Row -->
					<div class="row-fluid">		
						<!-- Column -->
						<div class="span6">							
							<!-- Group -->
							<div class="control-group">

								<label class="control-label">App Name</label>

								<div class="controls">

									<input type="text" name="app_name" id="app_name" value="<?php echo (!empty($this->appDetails['app_name'])?$this->appDetails['app_name']:''); ?>" readonly="true" class="span10" />
								</div>

							</div>
							<div class="control-group">

								<label class="control-label">Domain Name</label>

								<div class="controls">

									<input type="text" name="domain_name" id="domain_name" value="<?php echo (!empty($this->appDetails['domain_name'])?$this->appDetails['domain_name']:''); ?>" readonly="true" class="span10" />
								</div>

							</div>

							<div class="control-group">

								<label class="control-label">App Status</label>

								<div class="controls">

									<select class="span12" name="status">
										<option <?php echo ($this->appDetails['status']==1)?'selected':''; ?> value="1">Live</option>
										<option <?php echo ($this->appDetails['status']==2)?'selected':''; ?> value="2">Pending</option>
										<option <?php echo ($this->appDetails['status']==0)?'selected':''; ?> value="0">Inactive</option>
									</select>	

								</div>

							</div>

							<!-- // Group END -->      

						</div>
					</div>
					
					<div class="separator line bottom"></div>
					<div class="form-actions" class="margin-none">
						<button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok" ><i></i>Save changes</button>
						
						<a href="<?php $this->baseUrl(); ?>/admin/api/app-user-details">
						<button type="button" class="btn btn-icon btn-default glyphicons circle_remove"><i></i>Cancel</button> </a>
					</div>

					<!-- // Form actions END -->

					

				</div>

				<!-- // Tab content END -->

			</div>

		</form>

	</div>

</div>

<!-- // Widget END -->

	</div>	
</div>
<script>
    $('#menu_api').removeClass('collapse').addClass('in collapse');
    $('#api_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons list active');
    $('#menu_api_1').addClass('active');    
</script>
