
<script type="text/javascript" language="javascript" class="init">


$(document).ready(function() {
	$('#appusertable').dataTable( {
		columnDefs: [ {
			targets: [ 0 ],
			orderData: [ 0, 1 ]
		}, {
			targets: [ 1 ],
			orderData: [ 1, 0 ]
		}, {
			targets: [ 4 ],
			orderData: [ 4, 0 ]
		} ]
	} );
} );

</script>
<div id="content">
	<h4>App User Details</h4>
	<div class="innerLR">

		<!-- Widget -->
		<div class="widget">
			
			<!-- Widget heading -->
			<div class="widget-head">
				<h4 class="heading">App User Manage</h4>
			</div>
			<!-- // Widget heading END -->
			
			<div class="widget-body">
			
				<!-- Table -->
				<table id="appusertable" class="dynamicTable table table-striped table-bordered table-condensed">
				
					<!-- Table heading -->
					<thead>
						<tr>
							<th>No</th>
							<th>App Name</th>
							<th>Domain Name</th>
							<th>AppId</th>
							<th>SecretId</th>
							<th>App Description</th>
							<th class="center">Status</th>
							<th class="center">Action</th>
						</tr>
					</thead>
					<!-- // Table heading END -->
					
					<!-- Table body -->
					<tbody>				
						<!-- Table row -->
						<?php  if(isset($this->appDetails)): $row = 0; foreach($this->appDetails as $appDetails): $row ++;?>
						<tr class="gradeA">
							<td><?php echo $row; ?></td>
							<td><?php if(isset($appDetails['app_name'])) { echo $appDetails['app_name']; }else{ echo "N/A"; } ?></td>
							<td><?php echo $appDetails['domain_name']; ?></td>
							<td><?php echo $appDetails['appId']; ?></td>
							<td><?php echo $appDetails['secretId']; ?></td>
							<td><?php echo $appDetails['app_desc']; ?></td>
							<td class="center"><?php echo ($appDetails['status']==1)?"<span style='color:green;'>Live</span>":(($appDetails['status']==2)?"<span style='color:blue;'>Pending</span>":"<span style='color:red;'>Inactive</span>");?></td>
							<td class="center">
								<a title="Edit" href="/admin/change-app-status/<?php echo $appDetails['user_id']; ?>/<?php echo $appDetails['id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>&nbsp;
								
							</td>
						</tr>
						<?php endforeach;  endif; ?>
						<!-- // Table row END -->
						
						
						
					</tbody> 
					<!-- // Table body END -->
					
				</table>
				<!-- // Table END -->
				
			</div>
		</div>
	</div>	
</div>
<script>
    $('#menu_api').removeClass('collapse').addClass('in collapse');
    $('#api_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons list active');
    $('#menu_api_1').addClass('active');    
</script>
