
<div id="content">
    <h4>Depositor Details</h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading">Depositor Manage</h4>
            </div>
 <div>
<form id="transactionType"  name= transactionType action="" method="POST">
<input type="radio"  value="0" checked="" name="number"/>All
  &nbsp;  
<input type="radio"   value="1" name="number"/>Deposit
 &nbsp;  
<input type="radio"  value="2" name="number"/>withdraw
 &nbsp;  
<input type="radio"  value="3" name="number"/>FPP Reward
 &nbsp;  
<input type="radio"  value="4" name="number"/>Refund
   &nbsp;   
<input type="radio"   value="5" name="number"/>Winning
  &nbsp;  
<input type="radio" value="6" name="number"/>Entry fee
  &nbsp;  
<input type="radio"  value="7" name="number"/>bonus
 
</form>
</div>
            <!-- // Widget heading END -->

            <div class="widget-body">
 
                <!-- Table -->
                <table id="Mytransactioninfo"   cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>User Name</th>
                            <th>Pay Method</th>
                            <th>Amount</th>
                            <th>Confirmation Code</th>
                            <th>Transaction Date</th>                            
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody id="notrans">
                    <?php if(isset($this->transaction)): $row = 0; foreach($this->transaction as $depositorDetails): $row ++;?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $row; ?></td>
                            <td><?php echo $depositorDetails['user_name']; ?></td>
                            <td><?php echo $depositorDetails['transaction_type']; ?></td>
                            <td><?php echo $depositorDetails['transaction_amount']; ?></td>                            
                            <td><?php echo $depositorDetails['confirmation_code']; ?></td>
                            <td><?php echo date("j F Y ", strtotime($depositorDetails['transaction_date'])); ?></td>                            
                            
                        </tr>
                        <!-- // Table row END -->
                    <?php endforeach;  endif; ?>
                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>
<script>
    $('#menu_components1').removeClass('collapse').addClass('in collapse');
    $('#payment_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#payment_details_menu').addClass('active');
  //dev:priyanka varanasi  
  //date:25/11/2014
  //desc:paymentdetails
 $(document.body).on('change','#transactionType',function(e){
   var checked_site_radio = $('input:radio[name=number]:checked').val();
    //alert(checked_site_radio);
          $.ajax({            
                url      : './depositor-details',
                type     : 'POST',
                dataType : 'json',
                data : {
                    checked_site_radio:checked_site_radio
                },
                beforeSend : function() {

                },
                success : function(response) { 
                    $('#notrans').html(' ');
//               console.log(response);
//               console.log(typeof(response));
              if(response === 0){
                   $('#notrans').html('<h4 style="padding-left:10px;">No data found</h4>');
                }else  { 
                 var tab;
                          var t=0;
                           $.each(response,function( index, value ) {
                               t++;
//                               var tabhead = '<table  id ="Mytransactioninfo" class="dynamicTable table table-striped table-bordered table-condensed">'+
//                                 '<thead> <tr><th>No</th><th>User Name</th><th>Pay Method</th><th>Amount</th><th>Confirmation Code</th><th>Transaction Date</th>'+                           
//                                  '</tr> </thead><tbody>';
//                                           if(t === 1){$('#Mytransactioninfo').html(tabhead);}
                          var tab = '<tr class="gradeA"><td>'+t+'</td><td>'+value.user_name+'</td><td>'+value.transaction_type+'</td><td>'+value.transaction_amount+'</td>'+                            
                                    '<td>'+value.confirmation_code+'</td><td>'+value.transaction_date+'</td></tr>';
                   $('#notrans').append(tab);
                   
                     })
//                $('#Mytransactioninfo').append('</tbody>'); 
                  }
                  
  }     
  
  
            });
             if(checked_site_radio==0){
                  window.top.location = "./depositor-details";  
                  }
        }); 
          
</script>
