<div class="opennotificationGreen" style="z-index: 99;">	<span class="notification_msgGreen">All withdrawal request has been canceled successfully.</span></div><div id="content">
    <h4>Withdrawal Details</h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading">Withdrawal DFSCoin Details</h4>
            </div><br>
			<div class="col-md-12 col-sm-12">
				<div class="col-md-4 col-sm-4">
					
				</div>
				<div class="col-md-8 col-sm-8 pull-right" style="margin-right: 3%;">
					<a id="pay-button" class="btn btn-primary confirm-status" style="cursor:pointer;">Click To Pay</a>					
					<a id="cancel-button" class="btn btn-danger confirm-status" style="cursor:pointer;">Cancel Withdrawal Request</a>
				</div>
			</div><br>
            <!-- // Widget heading END -->
		
            <div class="widget-body">
				<form id="withdraw_table" action="" method="POST" >
                <!-- Table -->
                <table id="withdrawtab"  cellpadding="0" cellspacing="0" border="0" class=" table table-striped table-bordered">
					
                    <!-- Table heading -->
                    <thead>
                        <tr>
                            
                            <th><input type="checkbox" name="all" id="checkAll" /></th>
							<th>Sr. No.</th>
                            <th>User</th>
                            <th>Amount</th>
                            <th>Reciever DFSCoin Address</th>
                            <th>Request Date</th>
                            <th>Pay Date</th>
                            <th>Status</th>
                            <th>Transaction</th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
					
                    <tbody>      
                        <?php if(isset($this->paypalWithdraw)): $row = 0; 
						foreach($this->paypalWithdraw as $withdrawalDetails): $row ++;?>
                        <!-- Table row -->
                       
                        <tr class="gradeA">
                            
                            <td><?php if(empty($withdrawalDetails['transaction_id'])){ ?><input type="checkbox" name="withdrawalId[]" class="checkbox_class" value="<?php echo $withdrawalDetails['withdrawal_id']; ?>" /><?php } ?></td>
							<td><?php echo $row; ?></td>
							
                            <td><?php echo $withdrawalDetails['user_name']; ?></td>
							
                            <td><?php echo $withdrawalDetails['requested_amt']; ?></td>
							
                            <!--<td><?php if($withdrawalDetails['pay_method'] == '1'): echo "Paypal";endif; ?></td>-->
							
                            <td><?php echo $withdrawalDetails['account_no']; ?></td>
							
                            <td><?php echo date("j F Y, h:i:s A", strtotime($withdrawalDetails['request_date'])); ?></td>
							
                            <td><?php if($withdrawalDetails['status'] == '1'){ echo date("j F Y, h:i:s A", strtotime($withdrawalDetails['pay_date'])); }else{ echo "N/A"; } ?></td>
							
                            <td>
								<?php /* if($withdrawalDetails['status'] == '1'): echo "Completed"; else: echo '<a class="confirm-status" style="cursor:pointer;" amt='.$withdrawalDetails['requested_amt'].' email='.$withdrawalDetails['account_no'].' wid='.$withdrawalDetails['withdrawal_id'].' >Update</a>'; endif;
								*/
								if($withdrawalDetails['status'] == '1'): echo "Completed"; else: echo 'Pending'; endif; ?></td>
							
								<?php if($withdrawalDetails['status'] == '1'){ ?>
                            
									<td><?php if($withdrawalDetails['transaction_id'] != '0'): echo $withdrawalDetails['transaction_id']; else: echo "N/A"; endif; ?></td>
							
                            <?php }else{ ?>
							
								<td>
									
									<!--<a    target="_blank" href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_send-money&nav=1&email=<?php echo $withdrawalDetails['email']; ?>"><img src="http://www.paypal.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal"></a> -->
									<!--<a><button class="pointer paynow" data-id="<?php echo $withdrawalDetails['withdrawal_id']; ?>">PayNow</button></a>-->
									
									<a href="javascript:void(0);">N/A</a>
									
                                </td>
                                
                            <?php } ?>
                            
                             
                        </tr>
                        <?php endforeach;  endif; ?>
                        <!-- // Table row END -->                    

                    </tbody>
					
                    <!-- // Table body END -->

                </table>
				</form>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>

<div class="modal fade" id="cancel-withdraw" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">  
		<div class="modal-content"> 
			<div class="modal-header"> 
				<h4 class="modal-title" id="sendlabel" style="margin-top: 12px;">Confirm Your Action</h4>  
			</div>    
			<div class="modal-body">     
				<div class="panel panel-default">	
					<br>  
					<div class="panel-body"> 
					<label><h5>Are you sure you want to cancel selected withdraw request.</h5></label> 
					</div>		
					<br>      
				</div>		
				<div class="modal-footer">	
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>	
					<button type="button" class="btn btn-primary" id="cancel-confirm" data-id="" >Confirm</button>			
				</div>		
			</div>		
		</div>  
	</div>
</div>

<!---<div class="modal fade" id="pay-status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="sendlabel" style="margin-top: 12px;">Confirm Payment Status</h4>
            </div>
            <div class="modal-body">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <label><h5>Please confirm and verify Payment status from DFSCoin <span id="username" style="color:#926cff;"></span> </h5></label>
                        <hr>
                        <div class="row-fluid">
                            <label id="ret-msg" >Are you sure you have paid <span id="pay-money">20 DFSCoin</span> to registered DFSCoin Address : <span id="pay-mail">egeg&fbb</span></label>                
                            If Yes !! Then click on confirm OR cancel status update.
                            <label>Please provide the transaction Id for further records</label>
                            <input id="txnid" type="text" class="form-control span7" placeholder="DFSCoin transaction id" />
							<label id="txn_error" style="color:red; display:none;">* Please enter transaction Id.</label>
                        </div>
                    </div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="pay-confirm" data-id="" >Confirm</button>
            </div>
        </div>
           
    </div>
    </div>
</div>-->

<div class="modal fade" id="pay-status" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="sendlabel" style="margin-top: 12px;">Confirm Your Transaction</h4>
            </div>
            <div class="modal-body">
                <div class="panel panel-default">
					<br>
                    <div class="panel-body">
                        <label><h5>Are you sure want to pay all selected users request.</h5></label>
                        
                        
                    </div>
					<br>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="pay-confirm" data-id="" >Confirm</button>
            </div>
        </div>
           
    </div>
    </div>
</div>
<?php if(isset($this->success)){ ?>
<!-- This script Displays the  notification when the user details are submitted on submit  -->
<script>   
     	
	$('.opennotificationGreen').click(function()	{	
		$('.opennotificationGreen').fadeOut("slow");		
		$('div').remove(".notification_msgGreen");	
	});
	
	$('.opennotificationGreen').fadeIn("slow");   
	$('.opennotificationGreen').css('display','block');	
	
	setTimeout(function() {	
		$('.opennotificationGreen').fadeOut("slow");	
		$('div').remove(".notification_msgGreen");	
	}, 3000); 	
	
	setTimeout(function() { 
		window.location.replace("/admin/withdrawal-details");  
	}, 3000);
</script> 	
<?php } ?>	

<script>
    $('#menu_components1').removeClass('collapse').addClass('in collapse');
    $('#payment_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#withdrawal_details_menu').addClass('active');    
</script>
<script>
$(document).ready(function(){

	$('#withdrawtab').dataTable( {
		"aoColumnDefs": [{ "bSortable": false, "aTargets": [ 0,1,8] }],
		"order": [[ 1, "desc" ]]
	} );

    $(document.body).on('click','.confirm-status', function(e) {
		var atLeastOneIsChecked = false;
			$('.checkbox_class').each(function () {
				if ($(this).is(':checked')) {
				  atLeastOneIsChecked = true;
				  // Stop .each from processing any more items
				  return false;
				}
			});
			
			if(atLeastOneIsChecked){				
				var button_id = $(this).attr('id');		

				if(button_id=="pay-button"){	

					$('#pay-status').modal('show');		

				}else{			

					$('#cancel-withdraw').modal('show');	

				}
				
			}else{
				alert("Select atleast one record.");
			}
        
    });
    
	$('#pay-confirm').click(function(e) {
		$("#withdraw_table").attr('action','/admin/edit-status').submit();
	});		
	
	
	$('#cancel-confirm').click(function(e) {
		$("#withdraw_table").submit();
	});
	
    /* $(document.body).on('click','#pay-confirm', function(e) {
		 
        var wid = $(this).attr('data-id');
        var txnId = $('#txnid').val();
		if(txnId==''){
			$("#txn_error").show();
			setTimeout(function () {
               $("#txn_error").fadeOut("slow");
           }, 4000);
			return false;
		}
        if(wid){
			$.ajax({
				url      : '/admin/edit-status',
				type     : 'POST',
				dataType : 'json',
				data : {
					withdrawalId : wid,
					transactionId : txnId
				},
				success : function(response) {
					//alert(response.message);
					window.location.href = "/admin/withdrawal-details";
				}
		   });
        }
     }); */
	 
    $("#checkAll").click(function(){
		$('input:checkbox').not(this).prop('checked', this.checked);
	});
    
//  $(document.body).on('click','.paynow',function(){
//      var wtrId = $(this).attr('data-id');
//       $.ajax({
//            url      : '/admin/edit-status',
//            type     : 'POST',
//            dataType : 'json',
//            data : {
//                withdrawalId : wtrId
//            },
//            beforeSend : function() {
//
//            },
//            success : function(response) {
//                alert(response.message);
//                top.location.href = "/admin/withdrawal-details";
//            }
//       });
//  });  
})    
</script>