<div class="opennotificationGreen" style="z-index: 99;">
<span class="notification_msgGreen">Changes saved successfully.</span>
</div>

<div id="content">
    <h3>Edit Contest Promotion</h3>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget widget-tabs border-bottom-none">

            <!-- Widget heading -->
            <div class="widget-head">
                <ul>
                    <li class="active"><a class="glyphicons add" href="#" data-toggle="tab"><i></i>Update Contest Promotion</a></li>
                </ul>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">
                <form class="form-horizontal margin-none editcontestpromotion"  method="post">
                    <div class="tab-content pad0">

                        <!-- Tab content -->
                        <div class="tab-pane active" id="account-details">

                            <!-- Row -->
                            <div class="row-fluid">

                                <!-- Column -->
                                <div class="span10">

                                    <!-- Group -->
                                    <div class="control-group">
                                        <label class="control-label">Promotion Display Name</label>
                                        <div class="controls">
                                            <input type="text" name="promotion_display_name" id="promotion_display_name" value="<?php echo $this->editpromotion['promotion_display_name']?>" class="span6" readonly/>
                                        </div>
                                    </div>
                                    <!-- // Group END -->

                                    <!-- Group -->
                                    <div class="control-group">
                                        <label class="control-label">Promotion Content</label>
                                        <div class="controls">
                                            <textarea name="promotion_content" id="promotion_content"><?php echo $this->editpromotion['promotion_content']?></textarea>
                                        </div>
                                    </div>
                                    <!-- // Group END -->


                                    <!-- Group -->
                                    <div class="control-group">
                                        <label class="control-label">Status</label>
                                        <div class="controls">
                                            <select class="span4" name="status">
                                                <option  value="1" <?php if($this->editpromotion['status']==1){echo "selected";}?>>Active </option>                                                                                
                                                <option  value="0" <?php if($this->editpromotion['status']==0){echo "selected";}?>>Deactive</option>                                                                                
                                            </select>										
                                                <!--<span class="btn-action single glyphicons circle_question_mark margin-none" data-toggle="tooltip" data-placement="top" data-original-title="Last name is mandatory"><i></i></span>-->
                                        </div>
                                    </div>
                                    <!-- // Group END -->                                                                

                                </div>
                            </div>
                            <!-- // Row END -->

                            <div class="separator line bottom"></div>

                            <!-- Form actions -->
                            <div class="form-actions" class="margin-none">
                                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button>
                                <a href="<?php $this->baseUrl(); ?>/admin/contest-promotion/">	<button type="button" class="btn btn-icon btn-default glyphicons circle_remove"><i></i>Cancel</button> </a>
                            </div>
                            <!-- // Form actions END -->

                        </div>
                        <!-- // Tab content END -->

                    </div>
                </form>
            </div>
        </div>
        <!-- // Widget END -->

    </div>	
</div>
<script>
    $('#menu_components3').removeClass('collapse').addClass('in collapse');
    $('#promotion_setting_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons charts active');
    $('#contest_promotion_menu').addClass('active');    
</script>

    <?php if(isset($this->success)) {?>
<!-- This script Displays the  notification when the user details are submitted on submit  -->
<script>  
        $('.opennotificationGreen').click(function()
        {
//            alert('ss');
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        });
    
        $('.opennotificationGreen').fadeIn("slow");             
        $('.opennotificationGreen').css('display','block');
        
        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 3000); 
           setTimeout(function() {   
          window.location.replace("/admin/contest-promotion");   
        }, 3000); 
    </script>
    <?php }?>