<!DOCTYPE html>
<html>
    <body>
<div id="footer">
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-12">
                            <nav class="navbar navbar-inverse footerNav" role="navigation">
                                <div class="container">
                                    <ul class="nav nav-pills">
                                        <li class="active"><a href="#">Home</a></li>
                                        <li><a href="#">Lobby</a></li>
                                        <li><a href="#">My Lineups</a></li>
                                        <li><a href="#">My Contests</a></li>
                                    </ul>

                                </div>
                            </nav></div>
            <div class="col-md-12">
                <p class="footer-p">Copyright © 2013 DraftOff.com, powered by Epic Apps Inc.</p>
            </div>
        </div>

       
        
        
        
    </div>
  
  


    
    
</div>


<?php echo $this->render('script.phtml');  ?>

<script type="text/javascript">         
         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-8694286-1', 'krzysztof-furtak.pl');
            ga('send', 'pageview');
        </script>
        
</body>
</html>
<!--<iframe width="230px" height="368px" scrolling=no frameborder="0" src="http://www.soupnetworks.com/widget/feed-mlb"></iframe>-->