  

</div>
</div>


</div>      

</div>

<div id="footer">
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-12">
                            <nav class="navbar navbar-inverse footerNav" role="navigation">
                                <div class="container">
                                    <ul class="nav nav-pills">
                                        <li class="active"><a href="#">Home</a></li>
                                        <li><a href="#">Lobby</a></li>
                                        <li><a href="#">My Lineups</a></li>
                                        <li><a href="#">My Contests</a></li>
                                    </ul>

                                </div>
                            </nav>

                
            </div>
            <div class="col-md-12">
                <p>Copyright © 2013 DraftOff.com, powered by Epic Apps Inc.</p>
            </div>
        </div>

       
        
        
        
    </div>
  
  


    
    
</div>


<?php echo $this->render('script.phtml'); ?>

</body>
</html>