
<?php
if (isset($this->details)) {
    $details = $this->details;
}

?>

<div class="modal-header modal-header-pd-15">
<div class="row mr-15-right-left">
<div class="col-md-8 col-xs-12">
    <h3><?php
        if (isset($details['contest_name'])) {
            echo $details['contest_name'];
        }
        ?></h3>
    <ul class="list-unstyled list-inline">
        <li>  <?php
            if (isset($details['sports_id'])) {
                switch ($details['sports_id']) {
                    case 1 : echo "NFL";
                        break;
                    case 2 : echo "MLB";
                        break;
                    case 3 : echo "NBA";
                        break;
                    case 4 : echo "NHL";
                        break;
                }
            }
            ?></li>
        <li>Entries: <?php
            if (isset($details['total_entry'])) {
                echo $details['total_entry'];
            }
            ?> of <?php
            if (isset($details['play_limit'])) {
                echo $details['play_limit'];
            }
            ?></li>
        <li>Entry Fee: <?php
            if (isset($details['entry_fee'])) {
                if ($details['entry_fee'] == 0) {
                    echo "FREE";
                } else {
                    echo  $details['entry_fee'] . " DFS ";
                }
            }
            ?></li>
        <li>Prize Pool: <?php
            if (isset($details['prize_pool'])) {
                echo $details['prize_pool'] . " DFS";
            }
            ?></li>
        <li><?php
            if (isset($details['fpp'])) { 
                echo $details['fpp'];
            }
            ?> FPPS</li>
    </ul>
	</div>
    <div class="livesIn col-md-3 col-sm-3 col-xs-12 pull-right">
		<div id="countdown">
			<p id="head1">CONTEST LIVE IN</p>
			<div id='tiles'></div>
			<div class="labels">
				<li>Day</li>
				<li>Hour</li>
				<li>Min</li>
				<li>Sec</li>
			</div>
			<label><?php echo Date("F j, g:i a T", strtotime($this->details['start_time'])); ?></label>
		</div>
		<!--<p id="head1">CONTEST LIVE IN</p>
        <p class="timeleft1" counter="<?php echo strtotime($this->details['start_time']); ?>"></p>
        <label><?php echo Date("F j, g:i a T", strtotime($this->details['start_time'])); ?></label>-->
    </div>
    </div>
</div>
<div class="modal-body modal-body-1">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">Summary</h4>
                </div>
                <div class="panel-body">
                    <p><?php
                        if (isset($details['description'])) {
                            echo $details['description'];
                        }
                        ?></p>
                </div>
            </div>
            
        </div>
		
		<div class="col-sm-6 col-xs-12">
			<div class="panel">
					<div class="panel-heading">
						<div class="row">
							<div class="col-md-4">
								<h4 class="panel-title" style="margin-top: 7%;">Entrants</h4>
							</div>
							<div class="col-md-4 pd-left-none">
								<input type="text" name="entrants" class="form-control"  
									   value="<?php
									   if (isset($details['total_entry'])) {
										   echo $details['total_entry'] . ' of ';
									   }
									   if (isset($details['play_limit'])) {
										   echo $details['play_limit'];
									   }
									   ?> " readonly="" /> 
							</div>
							<div class="col-md-4 pd-left-none">
								<input type="text" id="rival-input" class="form-control" placeholder="FIND A RIVAL" />
								<a class="hidden rival-array"><?php print_r($this->username); ?> </a>
							</div>
						</div>                    
					</div>
					<div class="panel-body panel-body-a">
						<table class="table table-bordered" id="rivaldet">        
							<tbody class="user_name">
								<?php
								if (isset($this->username)) {
									foreach ($this->username as $key => $value) {
										?>
										<tr>
											<td> <?php
												echo $key;
												if ($value > 1) {
													?>
													<span  class="multiEntry" title="<?php echo $value; ?> entries">M</span>
												<?php } ?>
											</td>
										</tr>

										<?php
									}
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
            </div>
			
			
        <div class="col-sm-6 col-xs-12">
            <div class="panel">
                <div class="panel-heading">
                    <h4 class="panel-title">Prize Payouts</h4>
                </div>
                <div class="panel-body panel-body-a">
                    <div class="table-responsive">
                        <table class="table table-bordered">        
                            <thead >
                                <tr>
                                    <th> RANK</th>
                                    <th>PRIZES AWARDED</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($this->prize_details) && !empty($this->prize_details)) { 
                                    foreach ($this->prize_details as $key => $value) {
                                        ?>
                                        <tr>
                                            <td id="r"><?php
                                                if (isset($value['from'])) {
                                                    echo $value['from'];
                                                } if (isset($value['to'])) {
                                                    echo "-" . $value['to'];
                                                }
                                                ?></td>
                                            <td id="r"><?php
                                                if (isset($value['prize'])) {
                                                    echo $value['prize'];
                                                }
                                                ?></td>
                                        </tr>
                                    <?php
                                    }
                                }?>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <p>Visit 
        <?php
        if (isset($details['sports_id'])) {
            switch ($details['sports_id']) {
                case 1 : echo "<a style='color:#f85425 !important;' href=" . $this->baseUrl() . "/help/nfl" . ">NFL rules</a>";
                    break;
                case 2 : echo "<a style='color:#f85425 !important;' href=" . $this->baseUrl() . "/help/mlb" . ">MLB rules</a>";
                    break;
                case 3 : echo "<a style='color:#f85425 !important;' href=" . $this->baseUrl() . "/help/nba" . ">NBA rules</a>";
                    break;
                case 4 : echo "<a style='color:#f85425 !important;' href=" . $this->baseUrl() . "/help/nhl" . ">NHL rules</a>";
                    break;
            }
        }
        ?>
        for full contest scoring</p>
	</div>
    <div class="modal-footer">
		<div class="row text-center">
		
			<div class="col-md-2 col-xs-4 pd-15 col-md-offset-1 col-xs-offset-1">
				<button type="button"  class="btn btn-primary btn-lg btn-block" data-dismiss="modal">Close</button>
			</div>
			
			<?php if (isset($this->drafttype) && ($this->drafttype != 0)) { ?>
				<div class="col-md-2 pd-15 col-md-offset-6 col-xs-4 pd-15 col-xs-offset-2">
					<a href="<?php echo "/draftteam/" . $this->contest_id; ?>">
						<button type="button" class="btn btn-primary btn-lg btn-block" >Draft Now</button>   
					</a>
				</div>
			<?php } ?>
			
		</div>
        
		<div class="row" style="background-color:#f85425; height:10px;"> </div>
    </div>
    <script>
        onload = countdown();
        var gettime1 = '';
        function countdown() {
            var gettime1 = $('.timeleft1').attr('counter');
            updateTimeSpan1(gettime1, $('.timeleft1'));
        }
        function updateTimeSpan1(gettime1, selector) {

            var d = new Date(gettime1 * 1000);
            var t = new Date();
            var ms;
            var s, m, h;
            ms = d - t;

            // get hours    
            h = parseInt(ms / (1000 * 60 * 60));
            ms -= (h * 1000 * 60 * 60);
            // get minutes    
            m = parseInt(ms / (1000 * 60));
            ms -= (m * 1000 * 60);
            // get seconds    
            s = parseInt(ms / 1000);

            var time1 = h + 'h,' + m + 'm,' + s + 's.';
            $(selector).html(time1);
            setTimeout(function() {
                updateTimeSpan(gettime1, selector);
            }, 100);
        }




        
        /* desc:search box in the player detail modal to find the player who entered in the following contest */
        $(document).ready(function() {
            // Write on keyup event of keyword input element
            $("#rival-input").keyup(function() {
                // When value of the input is not blank
                var term = $(this).val().trim().toLowerCase();
                //alert(term);
                if (term != "")
                {
                    // Show only matching TR, hide rest of them
                    $("#rivaldet tbody>tr").hide();
                    $("#rivaldet td").filter(function() {
                        return $(this).text().toLowerCase().indexOf(term) > -1
                    }).parent("tr").show();
                }
                else
                {
                    // When there is no input or clean again, show everything back
                    $("#rivaldet tbody>tr").show();
                }
            });
        });
		

	//new timer

	//var target_date = new Date().getTime();  // set the countdown date
	var target_date = <?php echo (strtotime($this->details['start_time'])*1000); ?>;  // set the countdown date
	
	var days, hours, minutes, seconds; // variables for time units

	var countdown = document.getElementById("tiles"); // get tag element
	//countdown.innerHTML = "<span>34</span><span>23</span><span>23</span><span>23</span>"; 
	getCountdown();

	setInterval(function () { getCountdown(); }, 1000);
		
	function getCountdown(){

		// find the amount of "seconds" between now and target
		var current_date = new Date().getTime();
		
		var seconds_left = (target_date - current_date) / 1000;

		days = pad( parseInt(seconds_left / 86400) );
		seconds_left = seconds_left % 86400;
			 
		hours = pad( parseInt(seconds_left / 3600) );
		seconds_left = seconds_left % 3600;
			  
		minutes = pad( parseInt(seconds_left / 60) );
		seconds = pad( parseInt( seconds_left % 60 ) );

		/* format countdown string + set tag value */
		
		countdown.innerHTML = "<span>" + days + "</span><span>" + hours + "</span><span>" + minutes + "</span><span>" + seconds + "</span>"; 
	}

	function pad(n) {
		if(n>0){
			return (n < 10 ? '0' : '') + n;
		} else {
			return '00';
		}
	} 



    </script>
	
	
	
	
	
	
	