
	<div class="container mar-top">
		<div class="row">
			<div class="heading text-center">
				<h1>CREATE NEW CONTEST</h1>
			</div>
		</div>
	</div>
  
	<div class="container margin-40">
		<div class="row">
			<div class="well bg-image-1">
				<div class="bg-image-2">
					<div class="bs-example">
						<div class="row">
							<div class="col-md-12">
								<div class="text-center black-transparent paddingTB-sm m-top-md">
									<h2 class="text-blue no-margin">Pick a Game Type</h2>   
									<h3>What kind of game do you want to play?</h3>
								</div>
							</div>
						</div>

						<div class="black-transparent m-top-sm">
							<div class="row">
								<div class="col-sm-6">
								
									<div class="well margin-lg text-center bg-image min-h-250">
										<h4>TWO TEAMS GO TO HEAD-2-HEAD <br> ONLY ONE WILL SURVIVE</h4>
										<img src="<?php echo $this->baseUrl() . $this->theme_base_path?>/images/league-le.png" class="img-responsive center-block marginTB-md">
										<a href ="<?php echo $this->baseUrl('/new-contest/1'); ?>" class="pointer change_type" data-id="1">
										<button class="btn-submit btn-lg btn3d">HEAD TO HEAD</button></a>
									</div>
									
									<p class="text-center text-white">Challenge a friend or take on the world by posting in the lobby!</p>
									
								</div>
								
								<div class="col-sm-6">
								
									<div class="well margin-lg text-center bg-image min-h-250">
										<h4 class="text-white">DFS COMMISSIONERS!</h4>
										<img src="<?php echo $this->baseUrl() . $this->theme_base_path?>/images/league-league.png" class="img-responsive center-block marginTB-md">
										<a href ="<?php echo $this->baseUrl('/new-contest/2'); ?>" class="pointer change_type" data-id="1">
										<button class="btn-submit btn-lg btn3d">LEAGUE</button></a>
									</div>
									
									<p class="text-center text-white">Challenge a friend or take on the world by posting in the lobby!</p>
									
								</div>    
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
 