
<div class="container mar-top">    
<div class="row">
         <div class="heading text-center">
        <h1 class="text-white no-margin">   <?php
							if (isset($this->ctype)) {
							if ($this->ctype == 1) {
                                echo "HEAD-TO-HEAD CONTESTS";
                            } else {
                                echo "LEAGUE CONTESTS";
                            }
                        }
                        ?> </h1>
    </div>
    </div>
	</div>
    <div class="container margin-40">
        <div class="row">
			<div class="well bg-image-1"> 
				<div class="bg-image-2">									
                <div class="row">
                    <div class="col-sm-12">
                        <div class="padding-sm m-top-sm">
                            <div class="paddingLR-md text-white">
                                <p class="font-medium-a"><?php
                                    if (isset($this->ctype)) {
                                        if ($this->ctype == 1) {
                                            echo "Choose your settings below to set up a head-to-head contest in any sport, including fantasy football, baseball, basketball, and hockey! Challenge a friend or open it up to anyone. Win your rival's DraftCoins by proving your fantasy skills today!";
                                        } else {
                                            echo "Choose from the options below to set up a daily fantasy league in any sport, including football, baseball, basketball, and hockey. Play for your rivals' DraftCoins and, more importantly, for bragging rights among all your friends! ";
                                        }
                                    }
                                    ?> </p>
                            </div>
                            <div class="row">
                                <form method="post" class="margin-20">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label class="col-sm-3 text-center top5px font-medium-a"> Select Sport</label>
                                            <div class="input-group col-sm-9">
                                                <select class="form-control input-bg-black" name="sport" id="sports" required="true">
                                                    <option>Select Category</option>
                                                    <?php
                                                    if (isset($this->sportsDeatils)) {
                                                        foreach ($this->sportsDeatils as $sports){
                                                            ?>
                                                            <option value="<?php echo $sports['sports_id']; ?>"><?php echo $sports['display_name']; ?></option>
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </select>
                                                <div id="matcherr" style="color:red; display: none;">
                                                    <dt></dt>                    
                                                    <dd>No Match.</dd>
                                                </div>
                                            </div>


                                        </div>
                                        <div id="newcontest" style="display: none;">
                                            <div class="form-group">
                                                <label class="control-label text-right text-white m-top-xs col-xs-3">Time</label>
                                                <div class="input-group col-xs-9">
                                                    <select class="form-control custom-input input-bg-black" name="time" id="time" required="true">                                                        
                                                    </select>
                                                    <a class="showgamelist text-white">View Games</a>
                                                    <select class="form-control custom-input viewgames input-bg-black" name="viewgames" style="display: none;">                                                        
                                                    </select>
                                                </div>
                                            </div> 

                                            <!--                                                        <dd><a class="showgamelist">View Games</a></dd><br/>                    
                                                                                                    <dd>
                                                                                                        <select class="form-control custom-input viewgames" name="viewgames" style="display: none;">                                                        
                                                                                                        </select>                                               
                                                                                                    </dd>
                                                                                                    <dd> </dd><br/>-->

                                            <?php
                                            if (isset($this->ctype)) {
                                                if ($this->ctype == 2) {
                                                    ?>
                                                    <div class="form-group">
                                                        <label class="control-label text-right text-white m-top-xs col-xs-3">Size</label>         
                                                        <div class="input-group col-xs-9">
                                                            <select class="form-control custom-input input-bg-black" name="teamsize" id="teamsize">
                                                                <option value="3">3</option>
                                                                <option value="4">4</option>
                                                                <option value="5">5</option>
                                                                <option value="6">6</option>
                                                                <option value="7">7</option>
                                                                <option value="8">8</option>
                                                                <option value="9">9</option>
                                                                <option value="10">10</option>
                                                                <option value="11">11</option>
                                                                <option value="12">12</option>
                                                                <option value="13">13</option>
                                                                <option value="14">14</option>
                                                                <option value="15">15</option>
                                                                <option value="16">16</option>
                                                                <option value="17">17</option>
                                                                <option value="18">18</option>
                                                                <option value="19">19</option>
                                                                <option value="20">20</option>                     
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <?php
                                                }
                                            }
                                            ?>
                                            <div class="form-group">
                                                <label class="control-label text-right text-white m-top-xs col-xs-3">Entry</label>     
                                                <div class="input-group col-xs-9">
                                                    <select class="form-control custom-input input-bg-black" name="entryfee" id="entryfee" >
                                                        <option value="0">0</option>
                                                        <option value="1">1</option>
                                                        <option value="2">2</option>
                                                        <option value="5">5</option>
                                                        <option value="10">10</option>
                                                        <option value="20">20</option>
                                                        <option value="50">50</option>
                                                        <option value="109">109</option>
                                                        <option value="215">215</option>
                                                        <option value="530">530</option>
                                                        <option value="1060">1060</option>
                                                        <option value="5300">5300</option>                        
                                                    </select>
                                                </div>
                                            </div>
                                            <?php
                                            if (isset($this->ctype)) {
                                                if ($this->ctype == 1) {
                                                    ?>
                                                    <!--                    <dt>Count</dt>                    
                                                                        <dd>
                                                                            Number of challenges to create: 
                                                                            <select class="form-control" name="challengerCount" id="challengerCount">
                                                                                <option value="1">1</option>
                                                                                <option value="2">2</option>
                                                                                <option value="3">3</option>
                                                                                <option value="4">4</option>
                                                                                <option value="5">5</option>
                                                                                <option value="6">6</option>
                                                                                <option value="7">7</option>
                                                                                <option value="8">8</option>
                                                                                <option value="9">9</option>
                                                                                <option value="10">10</option>
                                                                                <option value="11">11</option>
                                                                                <option value="12">12</option>
                                                                                <option value="13">13</option>
                                                                                <option value="14">14</option>
                                                                                <option value="15">15</option>
                                                                                <option value="16">16</option>
                                                                                <option value="17">17</option>
                                                                                <option value="18">18</option>
                                                                                <option value="19">19</option>
                                                                                <option value="20">20</option>                        
                                                                            </select>
                                                                        </dd><br/>-->
                                                    <?php
                                                }
                                            }
                                            ?>

                                            <?php
                                            if (isset($this->ctype)) {
                                                if ($this->ctype == 2) {
                                                    ?>
                                                    <div class="form-group">
                                                        <label class="control-label text-right text-white m-top-xs col-xs-3">Prizes</label>     
                                                        <div class="input-group col-xs-9">          
                                                            <select class="form-control custom-input input-bg-black" name="prize" id="prize">
                                                                <?php
                                                                if (isset($this->ctype)) {
                                                                    if ($this->ctype == 1) {
                                                                        ?>
                                                                        <option value="1">Winner Takes All</option>
                                                                        <option value="2">Top 2 Win</option>  
                                                                    <?php } else { ?>
                                                                        <option value="1">Winner Takes All</option>
                                                                        <option value="2">Top 2 Win</option>
                                                                        <?php
                                                                    }
                                                                }
                                                                ?>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <?php
                                                }
                                            }
                                            ?>
                                            <?php
                                            if (isset($this->ctype)) {
                                                if ($this->ctype == 1) {
                                                    ?>
                                                    <!--                    <dt></dt>                    
                                                                        <dd>
                                                                            Limit the number of times one person can play against you. 
                                                                            <select class="form-control" name="numberofPerson" id="numberofPerson">
                                                                                <option value="0">Unlimited</option>
                                                                                <option value="1">1</option>
                                                                                <option value="2">2</option>
                                                                                <option value="3">3</option>
                                                                                <option value="4">4</option>
                                                                                <option value="5">5</option>
                                                                                <option value="6">6</option>
                                                                                <option value="7">7</option>
                                                                                <option value="8">8</option>
                                                                                <option value="9">9</option>
                                                                                <option value="10">10</option>
                                                                                <option value="11">11</option>
                                                                                <option value="12">12</option>
                                                                                <option value="13">13</option>
                                                                                <option value="14">14</option>
                                                                                <option value="15">15</option>
                                                                                <option value="16">16</option>
                                                                                <option value="17">17</option>
                                                                                <option value="18">18</option>
                                                                                <option value="19">19</option>
                                                                                <option value="20">20</option>    
                                                                            </select>
                                                                        </dd><br/>-->
                                                    <?php
                                                }
                                            }
                                            ?>
                                            </span>

                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">                                            
                                            <div class="input-group col-sm-12 text-white gametimes">
											<div class="row">
                                                <div class="radio">
                                                    <input type="radio" name="playwith" id="playwithFriend" value="0" checked>
                                                    <label for="playwithFriend"><span>Play with Friends</span></label>
                                                    <?php
                                                    if (isset($this->ctype)) {
                                                        if ($this->ctype == 2) {
                                                            ?>
                                                            <p class="font-medium-a">Create private contest</p>
                                                        <?php } else { ?>             
                                                            <?php
                                                        }
                                                    }
                                                    ?>
                                                </div>
                                                <div class="checkbox">
                                                    <input id="check" type="checkbox" value="" checked="">
                                                    <label for="check">
                                                        <span class="block">Find me an opponent if my challenge is not accepted.</span>
                                                    </label>
                                                </div>
                                                <div class="radio">
                                                    <input type="radio" name="playwith" id="playwithAnyone" value="1">
                                                    <label for="playwithAnyone"><span>Play Anyone</span></label>
                                                    <span class="block m-left-md">Your league will be posted in the game lobby. We will attempt to find you opponents if your challenge is not accepted prior to game time.</span>
                                                </div>
                                            </div>
                                            </div>
                                            <?php
                                            if (isset($this->ctype)) {
                                                if ($this->ctype == 2) {
                                                    ?>
                                                    <span class="block m-left-md font-medium-a">NOTE: This contest will not run and all entry fees will be refunded if the contest does not fill. </span>

                                                <?php } else { ?>

                                                    <p class="font-medium-a">NOTE: This contest will not run and all entry fees will be refunded if the contest does not fill. </p>

                                                    <?php
                                                }
                                            }
                                            ?>
                                        </div>
                                        <div>
                                            <a href="<?php echo $this->baseUrl('/direct-challenge'); ?>" class="btn-success btn-lg btn3d export_lineup" role="button">GO BACK</a>
                                            <button type="submit" class="btn-success btn-lg btn3d export_lineup">CREATE CONTEST >></button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>            

<input class="hidden" id="ctype" data-type="<?= $this->ctype; ?>">	
<style>    .input-bg-black {
    -moz-appearance: window;
    background-color: rgba(255, 255, 255, 0.2);
}
.input-bg-black {
   
    border: medium none !important;
    color: #fff;
}
    </style>
<script>


    //priyanka varanasi
    // dated: 8/11/2015
    // integrated scripts for this page 


    $(document.body).on('change', '#sports', function(e) {
        var sportsID = $(this).val();
        $.ajax({
            url: '/contest-ajax-handler',
            type: 'POST',
            dataType: 'json',
            data: {
                method: 'getcontestdata',
                sportsid: sportsID
            },
            beforeSend: function() {

            },
            success: function(response) {
                $("#time").empty();
                $(".viewgames").empty();

                if (response.code == '200') {
                    $("#newcontest").css('display', 'block');
                    $("#matcherr").css('display', 'none');
                    $.each(response.data, function(index, value) {
                        if (value > 1) {
                            $("#time").append('<option value="' + index + '">' + index + ' ' + value + ' games' + '</option>');
                        } else {
                            $("#time").append('<option value="' + index + '">' + index + ' ' + value + ' game' + '</option>');
                        }

                    });
                    $.each(response.gamesdata, function(index, value) {
                        $(".viewgames").append('<option value="' + index + '">' + index + '</option>');
                    });
                } else {
                    $("#newcontest").css('display', 'none');
                    $("#matcherr").css('display', 'block');
                }
            }
        });

    });

    $(document.body).on('click', '.showgamelist', function(e) {
        $('.viewgames').toggle('slow');

    });

    $(document.body).on('click', '#playwithFriend', function(e) {
        if ($('#playwithFriend').is(':checked')) {
            $('#name').show();
        }
    });

    $(document.body).on('click', '#playwithAnyone', function(e) {
        if ($('#playwithAnyone').is(':checked')) {
            $('#name').hide();
        }
    });



    /**
     * Developer     : Vivek Chaudhari   
     * Date          : 07/08/2014
     * Description   : change prize dropdown in contest create->leage
     **/
    $(document.body).on('change', '#teamsize', function() {
        var ctype = $('#ctype').attr('data-type');
        if (ctype == 2) {
            $('#prize').html('');
            $('#prize').append('<option value="1">Winner Takes All</option>');
            $('#prize').append('<option value="2">Top 2 Win</option>');
            var limit = $(this).val();
           
            if ((limit > 3) && (limit <= 5)) {
                $('#prize').append('<option value="3">Top 3 Win</option>');
            } else if (limit > 5) {
                $('#prize').append('<option value="3">Top 3 Win</option>');
                if (limit > 5) {
                    $('#prize').append('<option value="4">Top 5 Win</option>');
                }
            }
            if (limit % 2 == 0) {
                $('#prize').append('<option value="5">50/50</option>');
            }
        }
    });

    $(document.body).on('change', '#leagteamsize', function() {
        var ctype = $('#conType').val();
        if (ctype == 2) {
            $('#leagprize').html('');
            $('#leagprize').append('<option value="1">Winner Takes All</option>');
            $('#leagprize').append('<option value="2">Top 2 Win</option>');
            var limit = $(this).val();
            
            if ((limit > 3) && (limit <= 5)) {
                $('#leagprize').append('<option value="3">Top 3 Win</option>');
            } else if (limit > 5) {
                $('#leagprize').append('<option value="3">Top 3 Win</option>');
                if (limit > 5) {
                    $('#leagprize').append('<option value="4">Top 5 Win</option>');
                }
            }
            if (limit % 2 == 0) {
                $('#leagprize').append('<option value="5">50/50</option>');
            }
        }
    });

    ///code ends //
</script>