<div class="panel panel-default">
    <div class="panel-heading" style="color:#D40000;background-color: #FADBDB;border:1px solid #D40000; ">

        <h5 class="text-center" style="font-size: 12px;font-weight: bold;">
            No Offers Available for Your Country</h5>

        <h6 class="text-center" style="font-size: 11px">Currently, there are no available offers for this merchant in your country.</h6>

    </div>
    <div class="panel-body">
        <div class="row">            
            <div class="col-md-6">


            </div>            

        </div>
    </div>
</div>