<div class="container mar-top">
	<div class="row">
		<div class="heading text-center">
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab1a">
					<h1 id="headerTitle">DFSCOIN DEPOSIT CENTER!</h1>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container margin-40">

    <div class="row">
	
		<div class="btn-pref btn-group btn-group-1 btn-group-justified btn-group-lg" role="group" aria-label="...">
			
			<div class="btn-group" role="group">
				<a type="button" id="stars" class="btn btn-default btn-1" href="/account">
					<div class="hidden-xs-1">My <br />Account</div>
				</a>
			</div>
			
			<div class="btn-group" role="group">
				<a type="button" id="favorites" class="btn btn-default btn-1" href="/withdrawal">
					<div class="hidden-xs-1"> <br />Withdrawal</div>
				</a>
			</div>
			
			<div class="btn-group" role="group">
				<a type="button" id="favorites" class="btn btn-default btn-1" href="/transaction">
					<div class="hidden-xs-1">Account <br /> History</div>
				</a>
			</div>
			
			<div class="btn-group" role="group">
				<button type="button" id="stars" class="btn btn-1 active" href="#Deposit" data-toggle="tab" style=" border-right:none !important;">
				<div class="hidden-xs-1"> <br />Deposit</div>
				</button>
			</div>
		</div>
	  
	  
		<div class="well bg-image-1">
			<div class="tab-content">
			
          <div class="tab-pane fade in active" id="Deposit">
            <div class="row mr-15-right-left">
              <div class="bg-image-2">
                <h3>DEPOSIT DFSCoin TO YOUR DRAFTDAILY WALLET!</h3>
                <div class="row mr-15-right-left">
                  <div class="col-md-7 col-sm-7 col-xs-12 pd-15">
                    <h4 class="text-left">Follow the steps to continue to deposit:</h4>
                    <p class="font-medium-a">1: Please Copy This DFSCoin Wallet Address :<a href="javascript:void(0);"><?php echo ($this->adminDfsAddress)?$this->adminDfsAddress:"N/A";?></a></p>
                    <p class="font-medium-a">2: Pay Via Your Desktop Wallet To Given Wallet Address.</p>
                    <p class="font-medium-a">3: Copy Transaction Id From Your Wallet.</p>
                    <p class="font-medium-a">4: Click On Deposit Now Button.</p>
                    <p class="font-medium-a">5: A Modal will Open There Is Option To Put Transaction ID.</p>
                    <p class="font-medium-a">6: Press Submit To Make Transaction Complete.</p>
                    <p class="font-medium-a">7: Now Deposit Has Been Successfully Completed.</p>
					<div class="row mr-15-right-left">
                      <div class="col-md-6 col-sm-6 col-xs-8 pd-15">
                        <ul class="text-area">
                            <li class="font-medium-a">Play Today Win Today</li>
                            <li class="font-medium-a">No Hassle Withdraw</li>
                            <li class="font-medium-a">No season-long commitment</li>
                            <li class="font-medium-a">Trade DFSCoins For BTC</li>
                      </ul>
                    </div>
                    <div class="col-md-6 col-sm-6  col-xs-4 pd-15">
                        <ul class="text-area">
                         <li class="col-md-6 col-sm-6 col-xs-12 pd-15" style="list-style:none;"><img src="themes/draftdaily/skin/images/badge_satisfaction.png" alt="badge_satisfaction.png"/></li>
                      </ul>
                    </div>
                    </div>
                     </div>
                  <div class="col-md-5 col-sm-5 col-xs-12 pd-15">
                    <h4 class="text-left">Select amount</h4>
                    <div class="row mr-15-right-left">
                      <div class="col-md-6 col-sm-6 col-xs-6  pd-left-none pd-right-10">
                        <div class="background-image-a">
                          <div class="radio radio-1 radio-primary">
                            <input type="radio" name="radio1" id="radio1" value="option1">
                            <label for="radio1"> 2500 DFS</label>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6 col-sm-6 col-xs-6 pd-left-10 pd-right-none">
                        <div class="background-image-a">
                          <div class="radio radio-1 radio-primary">
                            <input type="radio" name="radio1" id="radio1" value="option1">
                            <label for="radio1"> 5000 DFS</label>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row mr-15-right-left">
                      <div class="col-md-6 col-sm-6 col-xs-6 pd-left-none pd-right-10">
                        <div class="background-image-a">
                          <div class="radio radio-1 radio-primary">
                            <input type="radio" name="radio1" id="radio1" value="option1">
                            <label for="radio1">10000 DFS</label>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6 col-sm-6 col-xs-6 pd-left-10 pd-right-none">
                        <div class="background-image-a">
                          <div class="radio radio-1 radio-primary">
                            <input type="radio" name="radio1" id="radio1" value="option1">
                            <label for="radio1">15000 DFS</label>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
					<span class="deposit-button"> 
						<a href="javascript:void(0);" class="btndpt" data-toggle="modal" data-target="#depositModal2"><button class="btn-submit btn-lg btn3d margin-10px" name="submit">DEPOSIT NOW</button></a>				  
					</span>
                  
                </div>
              </div>
            </div>
            <div class="row mr-15-right-left">				<div class="bg-image-3">					<div class="row">						<div class="col-md-6 col-sm-6 col-xs-12">							<p class="font-medium-a pull-left">DFSCoin is available on <a target="_blank" href="https://www.coinexchange.io/market/DFS/BTC">CoinExchange.io</a></p>						</div>						<div class="col-md-6 col-sm-6 col-xs-12">							<p class="font-medium-a text-right"> To Buy DFSCoin wtih BTC And Add to your account <a href="/purchase-dfscoin">Click here</a></p>						</div>					</div>				</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>