<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">

            <div class="col-md-2">
                <div class="well well-lg"><B>BHOJRAJ<BR>77.00</B></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>P<br>10</B></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>YTP<br>0</B></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>PIR<br>0</B></div> 
            </div>
            <div class="col-md-2">
                <div class="well well-lg"><b>$3,300,000<BR>CHAMPIONSHIP</b></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>PIR<br>0</B></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>YTP<br>0</B></div> 
            </div>
            <div class="col-md-1">
                <div class="well well-lg"><B>P<br>10</B></div> 
            </div>
            <div class="col-md-2">
                <div class="well well-lg">MATEXAS<BR><B>177.40</B></div> 
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-6">
                                <h5><B>CURRENTLY IN 1304TH</B></h5>
                            </div>
                            <div class="col-md-3">
                                <div class="btn-group ">
                                    <button type="button" class="btn btn-default">Bhojraj</button>
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        <span class="caret"></span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>

                                </div>
                            </div>
                            <div class="col-md-2">
                                <button type="button" class="btn btn-default btn-sm">VIEW 3+</button>
                            </div>
                        </div>


                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>POS</th>
                                    <th>NAME</th>
                                    <th>GAME</th>
                                    <th>SCORING</th>
                                    <th>FPTS</th>


                                </tr>
                            </thead>

                            <tbody class="user_name">

                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>



                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-6">

                            </div> 
                            <div class="col-md-6">
                                <h5><B>TOTAL FANTASY POINTS: 77.00</B></h5>
                            </div> 
                        </div> 


                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-6">
                                <h5><B>CURRENTLY IN 1ST</B></h5>
                            </div>

                            <div class="col-md-2">
                                <button type="button" class="btn btn-default btn-sm">REMATCH</button>
                            </div>

                            <div class="col-md-4">
                                <div class="btn-group ">
                                    <button type="button" class="btn btn-default">1-Matexas</button>
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        <span class="caret"></span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>

                                </div>
                            </div>

                        </div>


                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>POS</th>
                                    <th>NAME</th>
                                    <th>GAME</th>
                                    <th>SCORING</th>
                                    <th>FPTS</th>


                                </tr>
                            </thead>

                            <tbody class="user_name">

                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>
                                <tr>

                                    <td>P</td>
                                    <td>felix HernadezP</td>
                                    <td>Nym 2 PIT5<br> Final</td>
                                    <td>1HBP,4K,5ER,6IP</td>
                                    <td>5.5</td>

                                </tr>



                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> Hide Shared Players
                                    </label>
                                </div>  
                            </div> 
                            <div class="col-md-6">
                                <h5><B>TOTAL FANTASY POINTS: 178.00</B></h5>
                            </div> 
                        </div> 


                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h4><B>TOP LIVE CONTESTS</B></h4>

                    </div>

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>CONTEST NAME</th>
                                <th>RANK</th>



                            </tr>
                        </thead>

                        <tbody class="user_name">

                            <tr>

                                <td>PGA DAILY FREE CONTESTS</td>
                                <td>563/1287</td>


                            </tr>
                        </tbody>
                    </table>
                    <br>

                    <div class="row">
                        <div class="col-md-6">

                        </div>
                        <div class="col-md-6">
                            View All My Contests    
                        </div>
                    </div>
                    <br>

                </div>
            </div>


            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row"> 
                            <div class="col-md-10">
                                <h4><B>SCOREBOARD</B></h4>

                            </div>
                            <div class="col-md-1">
                                <span class="glyphicon glyphicon-chevron-left"></span>

                            </div>
                            <div class="col-md-1">
                                <span class="glyphicon glyphicon-chevron-right"></span>

                            </div>
                        </div>
                    </div>

                    <div class="row"> 
                        <div class="col-md-1">

                        </div>
                        <div class="col-md-2">
                            <div class="well well-lg"><B>FINAL</B><BR>MIA 3<BR><span class="glyphicon glyphicon-star"></span>PIT 5</div> 
                        </div>
                        <div class="col-md-2">
                            <div class="well well-lg"><B>FINAL</B><BR>NYM 2<BR><span class="glyphicon glyphicon-star"></span>PIT 5</div> 
                        </div>
                        <div class="col-md-2">
                            <div class="well well-lg"><B>FINAL</B><BR>CWS 0<BR><span class="glyphicon glyphicon-star"></span>PIT 7</div> 
                        </div>
                        <div class="col-md-2">
                            <div class="well well-lg"><B>FINAL</B><BR>WAS 3<BR><span class="glyphicon glyphicon-star"></span>PIT 5</div>
                        </div>
                        <div class="col-md-2">
                            <div class="well well-lg"><B>FINAL</B><BR>DET 6<BR><span class="glyphicon glyphicon-star"></span>PIT 0</div>
                        </div>  
                        <div class="col-md-1">

                        </div>
                    </div>
                </div>
            </div>
          </div>

        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h4><B>SPECIAL EVENTS</B></h4>
                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY<BR>FIVE FRIENDS YOU REFER<BR><button type="button" class="btn btn-warning">INVITE FRIENDS>></button></B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY<BR>FIVE FRIENDS YOU REFER<BR><button type="button" class="btn btn-warning">LEARN MORE>></button></B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY<BR>FIVE FRIENDS YOU REFER<BR><button type="button" class="btn btn-warning">LEARN MORE>></button></B></div> 
                        </div>
                    </div>

                </div>
            </div>


            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h4><B>AROUND THE LEAGUE</B></h4>
                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg"><B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY</B></div> 
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h5><B>TALK SOME SMACK</B></h5>
                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <div class="well well-lg">
                                <div class="col-xs-10">
                                    <input type="text" class="form-control" placeholder="Add comment...">
                                </div><br>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> Also post on Facebook
                                            </label>
                                        </div>
                                    </div>
                                </div><br>

                                <B>LIMITED TIME OFFER<BR>RECEIVE A $200 PERFECT<BR>GAME TICKET FOR EVERY<BR><button type="button" class="btn btn-primary">COMMENT</button></B></div> 
                        </div>
                    </div>

                </div>
             </div>
        </div>
