<style>
    #r {
        color: #333;
        background-color: rgb(234,234,235) !important;
    }
    #rivaldet th, #rivaldet td {
        color: #333;
    }
    .txt-blue {
        color: rgb(78,131,174) !important;
    }
    .bg-blue {
        background-color: rgb(78,131,174) !important;
    }
</style>

<div id="back" style="background-size: 200%;color:#FFFFFF;border:5px solid #000000;">
    <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
    <?php
    if (isset($this->details)) {
        $details = $this->details;
    }
    ?>
    <div class="panel panel-default" style="background-color: #232323; margin-bottom: 0;">
        <div class="bg-dark2" id="back" style="padding: 10px 15px;">
            <div class="navbar" id="back" style="margin-bottom: 0;">
                <div class="row" id="back">
                    <div class="col-md-8" id="back" style="color:#FFFFFF;">
                        <h4 id="head1" style="font-size: 20px;" class="txt-blue"><?php
    if (isset($details['contest_name'])) {
        echo $details['contest_name'];
    }
    ?></h4>
                        <h5>
                            <?php
                            if (isset($details['sports_id'])) {
                                switch ($details['sports_id']) {
                                    case 1 : echo "NFL";
                                        break;
                                    case 2 : echo "MLB";
                                        break;
                                    case 3 : echo "NBA";
                                        break;
                                    case 4 : echo "NHL";
                                        break;
                                }
                            }
                            ?>
                            <span>|</span>
                            Entries: <?php
                            if (isset($details['total_entry'])) {
                                echo $details['total_entry'];
                            }
                            ?>/
                            <?php
                            if (isset($details['play_limit'])) {
                                echo $details['play_limit'];
                            }
                            ?>
                            <span>|</span>
                            Entry Fee: <?php
                            if (isset($details['entry_fee'])) {
                                if ($details['entry_fee'] == 0) {
                                    echo "FREE";
                                } else {
                                    echo $details['entry_fee'] . "DFS";
                                }
                            }
                            ?>
                            <span>|</span>
                            Prize pool: <?php
                            if (isset($details['prize_pool'])) {
                                echo $details['prize_pool'];
                            }
                            ?>
                            <span>|</span>
<?php
if (isset($details['fpp'])) {
    echo $details['fpp'];
}
?>FPPS
                        </h5>
                    </div>

                    <div class="panel panel-default col-md-4 text-center bg-blue pull-right" id="back" style="border:1px solid #000000;width: 23.333%;color: #FFF; margin-right: 1.5%;">
                        <h5 id="head1" style="font-size: 16px;">CONTEST LIVE IN</h5>
                        <div class="timeleft2" counter="<?php echo strtotime($this->details['start_time']); ?>"></div>
                        <label><?php echo Date("F j, g:i a T", strtotime($this->details['start_time'])); ?></label>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body" style="background-color: #383838;">
            <div class="panel panel-default">
                <div class="panel-heading" id="conback">CONTEST DETAILS</div>
                <div class="row" style="background-color: #383838;">
                    <div class="col-md-8" >    
                        <div class="panel panel-default" style="background-color: #191919;">
                            <div class="panel-heading txt-blue" style="background-color: #000000;font-weight: bold;font-size: 18px;">SUMMARY</div>
                            <div class="panel-body" style="background-color: #191919;color:#FFFFFF;">
<?php
if (isset($details['description'])) {
    echo $details['description'];
}
?>
                            </div>
                            <div class="panel panel-default" style="background-color: #191919;">
                                <div class="panel-heading" style="background-color: #000000;">
                                    <div class="row" >
                                        <div class=" col-md-3 txt-blue" style="font-weight: bold;font-size: 18px;">ENTRANTS</div>
                                        <div class="col-md-4">
                                            <input type="text" name="entrants" class="form-control"  
                                                   value="<?php
                                                    if (isset($details['total_entry'])) {
                                                        echo $details['total_entry'] . '/';
                                                    }
                                                    if (isset($details['play_limit'])) {
                                                        echo $details['play_limit'];
                                                    }
                                                    ?> " readonly="">

                                        </div>
                                        <div class=" col-md-5" style="color:#FFFFFF">FIND A RIVAL <span><input type="text" id="rival-input" style="background-color: #000000;"><a class="hidden rival-array"><?php print_r($this->username); ?> </a></span></div>
                                    </div>
                                </div>
                                <div class="panel-body contestid">
                                    <table class="table table-striped table-bordered" id="rivaldet">        
                                        <tbody class="user_name">
<?php if (isset($this->username)) {
    foreach ($this->username as $key => $value) {
        ?>
                                                    <tr>
                                                        <td> <?php echo $key;
        if ($value > 1) {
            ?>
                                                                <span  class="multiEntry" title="<?php echo $value; ?> entries">M</span>
        <?php } ?>
                                                        </td>
                                                    </tr>

                                            <?php }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4" style="background-color: #383838;">
                        <div class="panel panel-default">
                            <div class="panel-heading txt-blue" style="background-color: #000000;font-weight: bold;font-size: 18px;">PRIZE PAYOUTS</div>
                            <div class="panel-body contest_detail" style="background-color: rgb(234,234,235);">
                                <table class="table table-striped table-bordered" style="background-color: #191919;">        
                                    <thead >
                                        <tr>
                                            <th> RANK</th>
                                            <th>PRIZES AWARDED</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                <?php if (isset($this->prize_details)) {
                    foreach ($this->prize_details as $key => $value) { ?>
                                                <tr>
                                                    <td id="r"><?php if (isset($value['from'])) {
                    echo $value['from'];
                } if (isset($value['to'])) {
                    echo "-" . $value['to'];
                } ?></td>
                                                    <td id="r"><?php if (isset($value['prize'])) {
                    echo $value['prize'];
                } ?></td>
                                                </tr>
    <?php }
} ?>
                                    </tbody>
                                </table>

                            </div>

                        </div>

                    </div>

                </div>
            </div>
            <p>visit 
<?php
if (isset($details['sports_id'])) {
    switch ($details['sports_id']) {
        case 1 : echo "<a href=" . $this->baseUrl() . "/help/nfl" . ">NFL rules</a>";
            break;
        case 2 : echo "<a href=" . $this->baseUrl() . "/help/mlb" . ">MLB rules</a>";
            break;
        case 3: echo "<a href=" . $this->baseUrl() . "/help/nba" . ">NBA rules</a>";
            break;
        case 4 : echo "<a href=" . $this->baseUrl() . "/help/nhl" . ">NHL rules</a>";
            break;
    }
}
?>
                for full contest scoring</p>
            <button type="button" class="btn btn-blue font-ste-regular p-bottom-sm pull-right" data-dismiss="modal">Close</button>
        </div>
    </div>

</div>
<script>
    //dev: priyanka varanasi
    //desc:integrated this page scripts 
    //date:14/8/2015
    onload = countdown();
  

    var gettime1 = '';
    function countdown() {
        var gettime1 = $('.timeleft2').attr('counter');
        console.log(gettime1);
        updateTimeSpan1(gettime1, $('.timeleft2'));
    }
      function updateTimeSpan1(gettime1, selector) {

        var d = new Date(gettime1 * 1000);
        var t = new Date();
        var ms;
        var s, m, h;
        ms = d - t;

        // get hours    
        h = parseInt(ms / (1000 * 60 * 60));
        ms -= (h * 1000 * 60 * 60);
        // get minutes    
        m = parseInt(ms / (1000 * 60));
        ms -= (m * 1000 * 60);
        // get seconds    
        s = parseInt(ms / 1000);

        var time1 = h + 'h,' + m + 'm,' + s + 's.';
        $(selector).html(time1);
        setTimeout(function() {
            updateTimeSpan1(gettime1, selector);
        }, 100);
    }



    //dev:priyanka varanasi
    //desc:search box in the player detail modal to find the player who entered in the following contest
    $(document).ready(function() {
        // Write on keyup event of keyword input element
        $("#rival-input").keyup(function() {
            // When value of the input is not blank
            var term = $(this).val().trim().toLowerCase();
            //alert(term);
            if (term != "")
            {
                // Show only matching TR, hide rest of them
                $("#rivaldet tbody>tr").hide();
                $("#rivaldet td").filter(function() {
                    return $(this).text().toLowerCase().indexOf(term) > -1
                }).parent("tr").show();
            }
            else
            {
                // When there is no input or clean again, show everything back
                $("#rivaldet tbody>tr").show();
            }
        });
    });

</script>
</script>
