

<div class="container mar-154 scroll_here">

    <div class="row">
		<div class="col-md-12 pd-15">
			<div id="main_area" class="main-area-2"> 
			<!-- Slider -->
          
				<div class="demo">
					<div class="item">
						<ul id="responsive" class="content-slider">
							<?php if (isset($this->activeOffers)) { ?>
							<?php foreach ($this->activeOffers as $value) { ?>
							
								<li> 
									<img src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . 'images/' . $value['image_url']; ?>" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P><?php echo $value['description']; ?></P>
										<a href="<?php echo "/draftteam/".$value['contest_id']; ?>" class="pull-right">Play Now<i class="fa fa-chevron-right" aria-hidden="true"></i></a>
									</div> 
								</li>
							
							<?php } ?>
							<?php } ?>
								
								<li style="cursor:default;"> 
									<img src="assets/images/offers/default/draft-2.jpg" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P id="bubble2">DRAFT YOUR TEAM</P>
									</div>
									
								</li>
								
								<li style="cursor:default;"> 
									<img src="assets/images/offers/default/draft-4.jpg" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P id="bubble3">DRAFT YOUR TEAM</P>
									</div>
									
								</li>
								
								<li style="cursor:default;"> 
									<img src="assets/images/offers/default/draft.jpg" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P id="bubble4">ENTER A CONTEST</span></P>
									</div>
									
								</li>
								<li style="cursor:default;"> 
									<img src="assets/images/offers/default/draft-5.jpg" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P id="bubble5">DRAFT YOUR TEAM</P>
									</div>
									
								</li>
								
								<li style="cursor:default;"> 
									<img src="assets/images/offers/default/draft-2.jpg" alt="offer-img.jpg" />
									
									<div class="play-now">
										<P id="bubble2">DRAFT YOUR TEAM</P>
									</div>
									
								</li>
								
						</ul>
					</div>
				</div>
          
			<!--/Slider-->           
			</div>
		</div>
    </div>
	
	
	
</div>

 <div class="container">
 <h3 class="text-center text-white">ACTIVE CONTEST</h3>
 </div> 
<div class="container margin-40">
    <div class="row">
		<div class="col-sm-2 col-md-2 col-xs-4 pd-15 sidebar">
			<div class="mini-submenu" id="menu-opener">
				<span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>
			</div>
			<div class="list-group" id="sort-option">
				<span href="#" class="list-group-item">
					Sort Contest By
					<span class="pull-right" id="slide-submenu">
						<i id="rotate-180" class="fa fa-chevron-left" aria-hidden="true"></i>
					</span>
				</span>
				<div class="background-image">
					<h5>Sports</h5>
					<select class="font-ste-medium contest-sport contest-sport-1" id="sportfilter">
						<option value="-1">Select Sports</option>
						<?php
						if (isset($this->sport)) {
							foreach ($this->sport as $sport) {
								echo "<option value=" . $sport['sports_id'] . ">" . $sport['display_name'] . "</option>";
							}
						}
						?>
					</select>
			  
					<h6>Entry fee</h6>
					<select class="font-ste-medium contest-sport contest_fee" id="from_con_val">
						<option value="-1">Free</option>
						<option value="101">101</option>
						<option value="201">201</option>
						<option value="501">501</option>
						<option value="1001">1001</option>
					</select>
					
					<span>TO</span>
					<select class="font-ste-medium contest-sport contest_fee" id="to_con_val">
						<option value="100">100</option>
						<option value="200">200</option>
						<option value="500">500</option>
						<option selected value="10000">10000</option>
					</select>
					
					<h6>Contest Types</h6>
					<ul id="nav-tabs-wrapper" class="nav nav-tabs nav-pills nav-stacked well well-1">
						<li class="active scroll_top"><a href="#allTab" data-toggle="tab">All</a></li>
						<li class="scroll_top"><a href="#guaranteedTab" data-toggle="tab">Guaranteed</a></li>
						<li class="scroll_top"><a href="#qualifiersTab" data-toggle="tab">Qualifiers</a></li>
						<li class="scroll_top"><a href="#headToHeadTab" data-toggle="tab">Head to Head</a></li>
						<li class="scroll_top"><a href="#fiftyFiftyTab" data-toggle="tab">50 - 50</a></li>
						<li class="scroll_top"><a href="#leaguesTab" data-toggle="tab">Leagues</a></li>
						<li class="scroll_top"><a href="#multipliersTab" data-toggle="tab">Multipliers </a></li>
					</ul>
					
					<div class="nav-side-menu">
						<div class="brand">Advanced Filters</div>
							<i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
							<div class="menu-list">
								<ul id="menu-content" class="menu-content collapse collapse-1 out">
								
								<li  data-toggle="collapse" data-target="#products" class="collapsed active"> <a href="javascript:void(0);">Start time<span class="arrow"></span></a> </li>
									
								<div class="sub-menu collapse collapse-2" id="products">
									
									<div class="radio radio-primary">
										<input checked class="contest_start scroll_top" id="rd1" type="radio" name="sTime" value="1">
										<label for="rd1"> All </label>
									</div>
									
									<div class="radio radio-primary">
										<input class="contest_start scroll_top" id="rd2" type="radio" name="sTime" value="2">
										<label for="rd2"> Next Start </label>
									</div>
									
									<div class="radio radio-primary">
										<input class="contest_start scroll_top" id="rd3" type="radio" name="sTime" value="3">
										<label for="rd3"> Today </label>
									</div>
									
								</div>
									
								<li data-toggle="collapse" data-target="#service" class="collapsed"> <a href="javascript:void(0);">Sizes <span class="arrow"></span></a> </li>
					
								<div class="sub-menu collapse collapse-2" id="service">
									
									<div class="checkbox">
										<input class="contest_size scroll_top" id="check1" type="checkbox" name="sizes" value="2-2">
										<label for="check1"> 02 </label>
									</div>
									
									<div class="checkbox">
										<input class="contest_size scroll_top" id="check2" type="checkbox" name="sizes" value="3-6">
										<label for="check2"> 03-06 </label>
									</div>
									
									<div class="checkbox">
										<input class="contest_size scroll_top" id="check3" type="checkbox" name="sizes" value="7-10">
										<label for="check3"> 07-10 </label>
									</div>
									
									<div class="checkbox">
										<input class="contest_size scroll_top" id="check4" type="checkbox" name="sizes" value="11-20">
										<label for="check4"> 11-20 </label>
									</div>
									
									<div class="checkbox">
										<input class="contest_size scroll_top" id="check5" type="checkbox" name="sizes" value="21-+">
										<label for="check5"> 21+ </label>
									</div>
									
								</div>
					
								<li class="collapsed text-center scroll_top"> <a id="clear_filter" href="javascript:void(0);">Clear Filters</a> </li>

							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	  
		<div class="col-sm-2 col-md-2 col-xs-4 pd-15">
		</div>
		<div class="col-sm-12 col-md-12 col-xs-12 pd-15" id="rightTabs">
			<div class="tab-content card-bca">
				<div role="tabpanel" class="tab-pane fade in active" id="allTab">
					<table class="footable datatable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->allcontest)) {
								foreach ($this->allcontest as $all) {
									if (isset($all['todayStart'])) {
										echo "<tr sport=" . $all['sports_id'] . " size=" . $all['play_limit'] . " fee=" . $all['entry_fee'] ." start=" . $all['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $all['sports_id'] . " size=" . $all['play_limit'] . " fee=" . $all['entry_fee'] ." start='' >";
									}
									
									?>	
									<td>
									<?php 
									
									if ($all['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($all['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($all['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($all['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $all['contest_id']; ?>">
									<span>
									<?php if($all['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $all['contest_name']; ?><?php if($all['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $all['total_entry'] . " of " . $all['play_limit']; ?></span></td>
									<?php
									
									if ($all['entry_fee']) {
										echo "<td><span>" . $all['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $all['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($all['start_time']) . ">" . $all['start_time'] . "</span></td>";
										
									if (isset($all['entry_type'])) {
										switch ($all['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $all['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$all['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $all['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
				
				<div role="tabpanel" class="tab-pane fade" id="guaranteedTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
						<?php
						if(!empty($this->grtd)) {
							foreach ($this->grtd as $grtd) {
								if (isset($grtd['todayStart'])) {
									echo "<tr sport=" . $grtd['sports_id'] . " size=" . $grtd['play_limit'] . " fee=" . $grtd['entry_fee'] ." start=" . $grtd['todayStart'] . " >";
								} else {
									echo "<tr sport=" . $grtd['sports_id'] . " size=" . $grtd['play_limit'] . " fee=" . $grtd['entry_fee'] ." start='' >";
								}
								
								?>							
								<td>
								<?php 
								
								if ($grtd['sports_id'] == 1) {
									echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
								} else if ($grtd['sports_id'] == 2) {
									echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
								} else if ($grtd['sports_id'] == 3) {
									echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
								} else if ($grtd['sports_id'] == 4) {
									echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
								}
								
								?>
								</td>
								<td>
								
								<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $grtd['contest_id']; ?>">
								<span>
								<?php if($grtd['is_featured'] == 1){ ?>
									<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
								<?php } ?>
								<?php echo $grtd['contest_name']; ?><?php if($grtd['entry_type'] == 3) { ?>
									<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
								<?php } ?></span></a>
								
								</td>
								
								<td><span><?php echo $grtd['total_entry'] . " of " . $grtd['play_limit']; ?></span></td>
								<?php
								
								if ($grtd['entry_fee']) {
									echo "<td><span>" . $grtd['entry_fee'] ."&nbsp;DFS</span></td>";
								} else {
									echo "<td><span>Free</span></td>";
								}
								
								echo "<td><span>" . $grtd['prize_pool'] ."&nbsp;DFS</span></td>";
								echo "<td><span class='timeleft' data-time=" . strtotime($grtd['start_time']) . ">" . $grtd['start_time'] . "</span></td>";
									
								if (isset($grtd['entry_type'])) {
									switch ($grtd['entry_type']) {
										case 1:
											echo "<td><a href='/draftteam/" . $grtd['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
											break;
										case 2: //user already enter into contest ask for edit lineup
											$uri = "/edit-contest-lineup/".$grtd['lineup_id'];
											echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
											break;
										case 3: //this is multientry contest , allow user to enter again
											echo "<td><a href='/draftteam/" . $grtd['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
											break;
										case 4:// user entered into contest with multientry, limit is complete
											echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
											break;
										case 5: //nobody can enter , entry is full
											echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
											break;
									}
								}
							}
						} else { ?>
							<tr>
								<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
							</tr>
						<?php }     ?>
					</tbody>
					</table>
				</div>
				
				
				<div role="tabpanel" class="tab-pane fade in" id="qualifiersTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->qual)) {
								foreach ($this->qual as $qual) {
									if (isset($qual['todayStart'])) {
										echo "<tr sport=" . $qual['sports_id'] . " size=" . $qual['play_limit'] . " fee=" . $qual['entry_fee'] ." start=" . $qual['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $qual['sports_id'] . " size=" . $qual['play_limit'] . " fee=" . $qual['entry_fee'] ." start='' >";
									}
									
									?>							
									<td>
									<?php 
									
									if ($qual['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($qual['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($qual['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($qual['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $qual['contest_id']; ?>">
									<span>
									<?php if($qual['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $qual['contest_name']; ?><?php if($qual['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $qual['total_entry'] . " of " . $qual['play_limit']; ?></span></td>
									<?php
									
									if ($qual['entry_fee']) {
										echo "<td><span>" . $qual['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $qual['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($qual['start_time']) . ">" . $qual['start_time'] . "</span></td>";
										
									if (isset($qual['entry_type'])) {
										switch ($qual['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $qual['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$qual['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $qual['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
			  
				<div role="tabpanel" class="tab-pane fade in" id="headToHeadTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->h2h)) {
								foreach ($this->h2h as $h2h) {
									if (isset($h2h['todayStart'])) {
										echo "<tr sport=" . $h2h['sports_id'] . " size=" . $h2h['play_limit'] . " fee=" . $h2h['entry_fee'] ." start=" . $h2h['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $h2h['sports_id'] . " size=" . $h2h['play_limit'] . " fee=" . $h2h['entry_fee'] ." start='' >";
									}
									
									?>							
									<td>
									<?php 
									
									if ($h2h['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($h2h['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($h2h['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($h2h['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $h2h['contest_id']; ?>">
									<span>
									<?php if($h2h['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $h2h['contest_name']; ?><?php if($h2h['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $h2h['total_entry'] . " of " . $h2h['play_limit']; ?></span></td>
									<?php
									
									if ($h2h['entry_fee']) {
										echo "<td><span>" . $h2h['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $h2h['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($h2h['start_time']) . ">" . $h2h['start_time'] . "</span></td>";
										
									if (isset($h2h['entry_type'])) {
										switch ($h2h['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $h2h['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$h2h['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $h2h['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
			  
				<div role="tabpanel" class="tab-pane fade in" id="fiftyFiftyTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->fft)) {
								foreach ($this->fft as $fft) {
									if (isset($fft['todayStart'])) {
										echo "<tr sport=" . $fft['sports_id'] . " size=" . $fft['play_limit'] . " fee=" . $fft['entry_fee'] ." start=" . $fft['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $fft['sports_id'] . " size=" . $fft['play_limit'] . " fee=" . $fft['entry_fee'] ." start='' >";
									}
									
									?>							
									<td>
									<?php 
									
									if ($fft['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($fft['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($fft['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($fft['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $fft['contest_id']; ?>">
									<span>
									<?php if($fft['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $fft['contest_name']; ?><?php if($fft['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $fft['total_entry'] . " of " . $fft['play_limit']; ?></span></td>
									<?php
									
									if ($fft['entry_fee']) {
										echo "<td><span>" . $fft['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $fft['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($fft['start_time']) . ">" . $fft['start_time'] . "</span></td>";
										
									if (isset($fft['entry_type'])) {
										switch ($fft['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $fft['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$fft['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $fft['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
			  
				<div role="tabpanel" class="tab-pane fade in" id="leaguesTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->leag)) {
								foreach ($this->leag as $leag) {
									if (isset($leag['todayStart'])) {
										echo "<tr sport=" . $leag['sports_id'] . " size=" . $leag['play_limit'] . " fee=" . $leag['entry_fee'] ." start=" . $leag['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $leag['sports_id'] . " size=" . $leag['play_limit'] . " fee=" . $leag['entry_fee'] ." start='' >";
									}
									
									?>							
									<td>
									<?php 
									
									if ($leag['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($leag['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($leag['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($leag['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $leag['contest_id']; ?>">
									<span>
									<?php if($leag['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $leag['contest_name']; ?><?php if($leag['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $leag['total_entry'] . " of " . $leag['play_limit']; ?></span></td>
									<?php
									
									if ($leag['entry_fee']) {
										echo "<td><span>" . $leag['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $leag['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($leag['start_time']) . ">" . $leag['start_time'] . "</span></td>";
										
									if (isset($leag['entry_type'])) {
										switch ($leag['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $leag['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$leag['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $leag['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
		  
				<div role="tabpanel" class="tab-pane fade in" id="multipliersTab">
					<table class="footable">
						<thead>
							<tr class="header-img">
								<th data-class="expand">SPORT</th>
								<th data-class="expand conatest_width">CONTEST</th>
								<th data-hide="phone,tablet">ENTRIES</th>
								<th data-hide="phone,tablet"> ENTRY FEE </th>
								<th data-hide="phone,tablet"> PRIZE POOL </th>
								<th data-hide=""> LIVE IN </th>
								<th data-hide="phone,tablet"></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(!empty($this->mult)) {
								foreach ($this->mult as $mult) {
									if (isset($mult['todayStart'])) {
										echo "<tr sport=" . $mult['sports_id'] . " size=" . $mult['play_limit'] . " fee=" . $mult['entry_fee'] ." start=" . $mult['todayStart'] . " >";
									} else {
										echo "<tr sport=" . $mult['sports_id'] . " size=" . $mult['play_limit'] . " fee=" . $mult['entry_fee'] ." start='' >";
									}
									
									?>							
									<td>
									<?php 
									
									if ($mult['sports_id'] == 1) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/rugbyball.png'>";
									} else if ($mult['sports_id'] == 2) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/baseball.png'>";
									} else if ($mult['sports_id'] == 3) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/basketball.png'>";
									} else if ($mult['sports_id'] == 4) {
										echo "<img class='contest-icon' alt='contest-icon.png' width='18' height='18' src='" . $this->baseUrl() . $this->theme_base_path . "/images/nhlball.png'>";
									}
									
									?>
									</td>
									<td>
									
									<a class="pointer opencontestmodal" drafttype="1"  data-toggle="modal" data-cid="<?php echo $mult['contest_id']; ?>">
									<span>
									<?php if($mult['is_featured'] == 1){ ?>
										<i class="fa fa-star-o fa-2x" aria-hidden="true" title="Feature contest"></i>
									<?php } ?>
									<?php echo $mult['contest_name']; ?><?php if($mult['entry_type'] == 3) { ?>
										<i class="icon_class fa fa-maxcdn" aria-hidden="true" title="Multi Entry contest"></i>
									<?php } ?></span></a>
									
									</td>
									
									<td><span><?php echo $mult['total_entry'] . " of " . $mult['play_limit']; ?></span></td>
									<?php
									
									if ($mult['entry_fee']) {
										echo "<td><span>" . $mult['entry_fee'] ."&nbsp;DFS</span></td>";
									} else {
										echo "<td><span>Free</span></td>";
									}
									
									echo "<td><span>" . $mult['prize_pool'] ."&nbsp;DFS</span></td>";
									echo "<td><span class='timeleft' data-time=" . strtotime($mult['start_time']) . ">" . $mult['start_time'] . "</span></td>";
										
									if (isset($mult['entry_type'])) {
										switch ($mult['entry_type']) {
											case 1:
												echo "<td><a href='/draftteam/" . $mult['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 2: //user already enter into contest ask for edit lineup
												$uri = "/edit-contest-lineup/".$mult['lineup_id'];
												echo "<td><a href='$uri'><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 3: //this is multientry contest , allow user to enter again
												echo "<td><a href='/draftteam/" . $mult['contest_id'] . "' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/enter.png' alt='enter.png'/></a></td></tr>";
												break;
											case 4:// user entered into contest with multientry, limit is complete
												echo "<td><a href='/lineup' ><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/edit.png' alt='edit.png'/></a></td></tr>";
												break;
											case 5: //nobody can enter , entry is full
												echo "<td><a><img class='enter-img' src='" . $this->baseUrl() . $this->appSetting->assestPath ."draftdaily/img/entryfull.png' alt='entryfull.png'/></a></td></tr>";
												break;
										}
									}
								}
							} else { ?>
								<tr>
									<td colspan="6" style="text-align:center;" class="text-center">No contest found.</td>
								</tr>
							<?php }     ?>
						</tbody>
					</table>
				</div>
		  
			</div>
		</div>
    </div>
</div>
  
<input id="size" class="hidden" type="text" min ="2" max="10000">
<input id="fee" class="hidden" type="text"  min ="0" max="10000">
<script src="https://rawgit.com/WashingtonGuedes/jquery-bubble-text/master/jquery.bubble.text.js"></script>

<script>
$(document).ready(function() {
	
    var $element1 = $('#bubble1');
    var phrases = [
        'Win Real Money',
       
    ];
    var index = -1;
    (function loopAnimation() {
        index = (index + 1) % phrases.length;
        bubbleText({
            element: $element1,
            newText: phrases[index],
            letterSpeed: 70,
            callback: function() {
                setTimeout(loopAnimation, 1000);
            },
        });
    })();
	
	var $element2 = $('#bubble2');
    var phrases = [
        'Draft Your Team',
       
    ];
    var index = -1;
    (function loopAnimation() {
        index = (index + 1) % phrases.length;
        bubbleText({
            element: $element2,
            newText: phrases[index],
            letterSpeed: 70,
            callback: function() {
                setTimeout(loopAnimation, 1000);
            },
        });
    })();
	
	var $element3 = $('#bubble3');
    var phrases = [
        'Enter A Contest',
       
    ];
    var index = -1;
    (function loopAnimation() {
        index = (index + 1) % phrases.length;
        bubbleText({
            element: $element3,
            newText: phrases[index],
            letterSpeed: 70,
            callback: function() {
                setTimeout(loopAnimation, 1000);
            },
        });
    })();
	
	var $element4 = $('#bubble4');
    var phrases = [
        'Enter A Contest',
       
    ];
    var index = -1;
    (function loopAnimation() {
        index = (index + 1) % phrases.length;
        bubbleText({
            element: $element4,
            newText: phrases[index],
            letterSpeed: 70,
            callback: function() {
                setTimeout(loopAnimation, 1000);
            },
        });
    })();
	
	var $element5 = $('#bubble5');
    var phrases = [
        'Draft Your Team',
       
    ];
    var index = -1;
    (function loopAnimation() {
        index = (index + 1) % phrases.length;
        bubbleText({
            element: $element5,
            newText: phrases[index],
            letterSpeed: 70,
            callback: function() {
                setTimeout(loopAnimation, 1000);
            },
        });
    })();
});
	
	$(document).ready(function() {
		
		$('#sportfilter').change(function() {
			contestfilter();
		});
		
		$('.contest_start').change(function() {
			contestfilter();
		});
		
		$('.contest_size').click(function() {
			var tmpMin = false;
			var check = true;
			$.each($('.contest_size:checked'), function(value) {
				//its checked
				check = false;
				var data = $(this).val();
				var arr = data.split('-');
				if (!tmpMin) {
					$('#size').attr('min', arr[0]);
					tmpMin = true;
				}
				var last = $('.contest_size:checked:last').val();
				var arr = last.split('-');
				$('#size').attr('max', arr[1]);
				if (arr[1] == '+') {
					$('#size').attr('max', '10000');
				}
			});
			if (check) {
				$('#size').attr('max', 10000);
				$('#size').attr('min', 2);
			}
			contestfilter();
		});
		
		$(document.body).on('change', '.contest_fee', function(e) {
			var from_con_val = parseInt($("#from_con_val").val());
			var to_con_val = parseInt($("#to_con_val").val());
			
			if (from_con_val < to_con_val) {
				$('#fee').attr('max', to_con_val);
				$('#fee').attr('min', from_con_val);
			} else {
				$('#fee').attr('max', from_con_val);
				$('#fee').attr('min', to_con_val);
			}
			contestfilter();
		});

		var contestfilter = function() {
			var minSize = parseInt($('#size').attr('min'));
			var maxSize = parseInt($('#size').attr('max'));
			var minFee = parseInt($('#fee').attr('min'));
			var maxFee = parseInt($('#fee').attr('max'));

			var sport = $('#sportfilter').val();
			var start = $('.contest_start:checked').val();
			$.each($('tbody>tr'), function() {
				var csport = $(this).attr('sport');
				var size = parseInt($(this).attr('size'));
				var fee = parseInt($(this).attr('fee'));
				var cstart = $(this).attr('start');
				
				if(typeof(csport) != 'undefined'){
					console.log(csport);
					$(this).addClass('hidden');
				}
				if (size >= minSize && size <= maxSize && fee >= minFee && fee <= maxFee) {
					if (sport != '-1') {
						if (sport == csport) {
							if (start != '1') {
								if (start == cstart) {
									$(this).removeClass('hidden');
								}
							} else {
								$(this).removeClass('hidden');
							}
						}
					} else {
						if (start != '1') {
							if (start == cstart) {
								$(this).removeClass('hidden');
							}
						} else {
							$(this).removeClass('hidden');
						}
					}
				}
			});
		}; 
		
		$(document.body).on('click', '#clear_filter', function(e) {
			$('#size').attr('max', 10000);
			$('#size').attr('min', 2);
			$('#fee').attr('max', 10000);
			$('#fee').attr('min', 0);
			$('#rd1').prop('checked', true);
			
			$.each($('.contest_size'), function(value) {
				$(this).prop('checked', false);
			});
			
			$("#sportfilter option:first").attr('selected', 'selected');
			
			contestfilter();
		});	
		
	}); 
     
	
	//ready ends
    
	$(document.body).on('click', '.opencontestmodal', function() {
        var contestId = $(this).attr('data-cid');
        var drafttype = $(this).attr('drafttype');


        $.ajax({
            url: '/contest-details',
            type: 'POST',
            dataType: 'html',
            data: {
                cid: contestId,
                drafttype: drafttype
            },
            beforeSend: function() {

            },
            success: function(response) {
                $(document.body).find('#contestdetails_body').html(response)
                $('#contestModal').modal('show');
            }
        });

    });

	$(".scroll_top").click(function(e) { 
		// Prevent a page reload when a link is pressed
		//e.preventDefault(); 
		// Call the scroll function
		$('html,body').animate({scrollTop: $(".scroll_here").offset().top},'slow');  
		
	});
	
</script>

<script>
	$(document).ready(function() {
		/* $('.mini-submenu').hide();
		$(window).scroll(function(){
			var h = $(document).scrollTop();
			if(h>=356){
				$('.mini-submenu').show();
			}else{
				$('.mini-submenu').hide();
			}
			console.log(h);
		}); */
	   
	   $('#responsive').lightSlider({
			item:4,
			loop:false,
			slideMove:1,
			easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
			speed:600,
			responsive : [
				{
					breakpoint:800,
					settings: {
						item:2,
						slideMove:1,
						slideMargin:6,
					  }
				},
				{
					breakpoint:500,
					settings: {
						item:1,
						slideMove:1
					  }
				}
			]
		});  
	});
    
	$(function(){

		$('#slide-submenu').on('click',function() {			        
			$(this).closest('.list-group').fadeOut('slide',function(){
				$('.mini-submenu').fadeIn();	
			});
        
		});

		$('.mini-submenu').on('click',function(){		
			$(this).next('.list-group').toggle('slide');
			$('.mini-submenu').hide();
			$('#sort-option').toggleClass( "list-open");
			$('#sort-option').removeClass('list-close');
			$('#rotate-180').removeClass('fa-rotate-180');	
		});
	
	});
	
	$('#slide-submenu').on('click',function(){
		$('#rotate-180').addClass('fa-rotate-180');		
		$('#sort-option').addClass('list-close').removeClass('list-open');
	});
	
	table = $(".dataTable").DataTable({
			   "paging":   true,
			   "info":     false,
			   "searching": false
	});

</script>