
			<div class="container mar-top">
				<div class="row">
					<div class="heading text-center">
						<h1>DRAFT DAILY CRYPTO FANTASY SPORTS</h1>
						<h2>DAILY FANTASY NFL, MLB, NBA, NHL</h2>
					</div>
				</div>
			</div>


			<div class="container">
				<div class="row">
					<div class="col-md-6 pd-15">
						<div class="col-md-6 col-md-offset-3 pd-15">
							<ul class="landing-bullets">
								<li><span class="glyphicon glyphicon-play"></span> No season-long commitments</li>
								<li><span class="glyphicon glyphicon-play"></span> Draft new teams daily</li>
								<li><span class="glyphicon glyphicon-play"></span> Sign up for free</li>
								<li><span class="glyphicon glyphicon-play"></span> Win DFSCoins</li>
							</ul>
						</div>
						<div class="col-md-6 pd-15 col-md-offset-3">
							<a class="btn btn-positive text-center play-now-button" href="/signup">Play Now </a>
						</div>
					</div>

					<div class="col-md-6 pd-15">
						<iframe id="ytplayer" type="text/html" width="100%" height="350px"
							src="https://www.youtube.com/embed/j6FD3ut3XEM?rel=0&showinfo=0&color=white&iv_load_policy=3&autoplay=1"
							frameborder="0" allowfullscreen>
						</iframe>
					</div>
				</div>													
			</div>


			<div class="container">
				<div class="row">
					<div class="heading text-center margin-100">
						<h1>PLAY WITH DFSCoin ON DRAFT DAILY</h1>
						<p>DFSCoin is a decentrialized crypto currency like bitcoin for fantasy sports.</p>
					</div>
				</div>
			</div>


			<div class="container">
				<div class="row">
				
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50 pd-left-none">
						<div class="text-box text-center">
							<h3>50/50 CONTESTS</h3>
							<p>A 50/50 is a contest where the top 50% of the people win. Simply to finish in the top half of the field. </p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50">
						<div class="text-box text-center">
							<h3>DAILY/WEEKLY LEAGUES</h3>
							<p>DraftDaily.com hosts daily and weekly fantasy leagues ranging from 3 players up to thousands of players.</p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50">
						<div class="text-box text-center">
							<h3>HEAD-TO-HEAD</h3>
							<p>In a head-to-head contest you square off against another daily fantasy player to win DFSCoin.</p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50 pd-right-none">
						<div class="text-box text-center">
							<h3>QUALIFIER</h3>
							<p>A qualifier is a contest where the prize or prizes is free entry into another contest with a large prize pool.</p>
						</div>
					</div>
				</div>


				<div class="row">
				
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50 pd-left-none">
						<div class="text-box text-center">
							<h3>LARGER PAYOUTZONE</h3>
							<p>Earn commissions from the contest fees paid by players you refer, and the players they refer across 6 total tiers.</p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50">
						<div class="text-box text-center">
							<h3>MULTIPLIERS</h3>
							<p>Multipliers is a prize structure that signifies that those that place will win a “multiple” of their buy-in.</p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50">
						<div class="text-box text-center">
							<h3>STEPS TOURNAMENTS</h3>
							<p>Steps tounamnets are series of qualifiers. The first steps have a very small buy-in, the top steps have larger buy-ins and payout prizes.</p>
						</div>
					</div>
					
					<div class="col-md-3 col-sm-12 col-xs-12 pd-7 mb-50 pd-right-none">
						<div class="text-box text-center">
							<h3>REFER-A-FRIEND</h3>
							<p>Earn life time revenue share commissions everytime a player you refered plays in a paid contest. Our rev-share pays out 35%</p>
						</div>
					</div>
				</div>

				<div class="row mb-50">
					<div class="col-md-2 col-sm-2 col-xs-6 pd-15 col-md-offset-5 col-sm-offset-5 col-xs-offset-3">
						<a class="btn btn-positive text-center" href="/signup">Play Now </a>
					</div>
				</div>
			</div>
