    <section class="background-bg">
    	<div class="container">
        	<div class="panel panel-main">
            	<div class="panel-heading">
                	<h3 class="font-ste-regular">PROMOTIONS</h3>
                </div>
                <div class="panel-body">
                	<div class="row">
                    	<div class="col-md-12">
                        	<div>
                            	<img src="assets/images/img-2.png" class="img-responsive" width="100%" height="218">
                                
                                <p class="font-ste-regular text-uppercase font-24">Lorem ipsum dolor sit amet, consectetur adipiscing elit,</p>
                            </div>
                            
                            <div class="row m-top-md">
                            	<div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-3">
                                	<div>
                                    	<img src="assets/images/default_img.png" class="img-responsive" width="100%">
                                        
                                        <div>
                                        	<p class="font-ste-regular font-16">TITLE PROMO</p>
                                            
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet vulputate felis. Quisque quis lorem ut nibh dapibus mollis. Donec in risus mollis, vestibulum odio quis, aliquet ante. <span><a class="text-red" href="#">Read more >></a></span></p>
                                        </div>
                                    </div>
                                </div>
                            	
                            </div>
                            
                        </div>                    
                    </div>
                </div>
            </div>
            
           
        	
        </div>
    </section>

